# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.problem import Problem
from ...models.webhook_create import WebhookCreate
from ...models.webhook_created import WebhookCreated
from typing import cast


def _get_kwargs(
    *,
    body: WebhookCreate,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/v1/webhooks",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Problem | WebhookCreated | None:
    if response.status_code == 200:
        response_200 = WebhookCreated.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Problem | WebhookCreated]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: WebhookCreate,
) -> Response[Problem | WebhookCreated]:
    """Create a webhook (the signing secret is shown once)

     Register an HTTPS endpoint for a set of events. The response's `secret` is the only time it is ever
    shown -
    store it now. Deliveries are signed Standard-Webhooks style (`webhook-id`, `webhook-timestamp`,
    `webhook-signature`). Events of private projects are included.

    Args:
        body (WebhookCreate): The request body of `webhooks.create`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Problem | WebhookCreated]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: WebhookCreate,
) -> Problem | WebhookCreated | None:
    """Create a webhook (the signing secret is shown once)

     Register an HTTPS endpoint for a set of events. The response's `secret` is the only time it is ever
    shown -
    store it now. Deliveries are signed Standard-Webhooks style (`webhook-id`, `webhook-timestamp`,
    `webhook-signature`). Events of private projects are included.

    Args:
        body (WebhookCreate): The request body of `webhooks.create`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Problem | WebhookCreated
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: WebhookCreate,
) -> Response[Problem | WebhookCreated]:
    """Create a webhook (the signing secret is shown once)

     Register an HTTPS endpoint for a set of events. The response's `secret` is the only time it is ever
    shown -
    store it now. Deliveries are signed Standard-Webhooks style (`webhook-id`, `webhook-timestamp`,
    `webhook-signature`). Events of private projects are included.

    Args:
        body (WebhookCreate): The request body of `webhooks.create`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Problem | WebhookCreated]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: WebhookCreate,
) -> Problem | WebhookCreated | None:
    """Create a webhook (the signing secret is shown once)

     Register an HTTPS endpoint for a set of events. The response's `secret` is the only time it is ever
    shown -
    store it now. Deliveries are signed Standard-Webhooks style (`webhook-id`, `webhook-timestamp`,
    `webhook-signature`). Events of private projects are included.

    Args:
        body (WebhookCreate): The request body of `webhooks.create`.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Problem | WebhookCreated
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
