# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.problem import Problem
from ...models.webhook_out import WebhookOut
from ...models.webhook_update import WebhookUpdate
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    subscription_id: str,
    *,
    body: WebhookUpdate,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_match: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(authorization, Unset):
        headers["authorization"] = authorization

    if not isinstance(if_match, Unset):
        headers["If-Match"] = if_match

    params: dict[str, Any] = {}

    params["is_registration"] = is_registration

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "patch",
        "url": "/v1/webhooks/{subscription_id}".format(
            subscription_id=quote(str(subscription_id), safe=""),
        ),
        "params": params,
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Problem | WebhookOut | None:
    if response.status_code == 200:
        response_200 = WebhookOut.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Problem | WebhookOut]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    subscription_id: str,
    *,
    client: AuthenticatedClient,
    body: WebhookUpdate,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_match: str | Unset = UNSET,
) -> Response[Problem | WebhookOut]:
    """Change, pause, resume or re-enable a webhook

     Change the name, URL, events or projects; pause (`status: paused`) or resume (`active`). A webhook
    DISABLED after
    repeated failures is re-enabled with `status: active`, which resets its failure count.

    Args:
        subscription_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_match (str | Unset):
        body (WebhookUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Problem | WebhookOut]
    """

    kwargs = _get_kwargs(
        subscription_id=subscription_id,
        body=body,
        is_registration=is_registration,
        authorization=authorization,
        if_match=if_match,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    subscription_id: str,
    *,
    client: AuthenticatedClient,
    body: WebhookUpdate,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_match: str | Unset = UNSET,
) -> Problem | WebhookOut | None:
    """Change, pause, resume or re-enable a webhook

     Change the name, URL, events or projects; pause (`status: paused`) or resume (`active`). A webhook
    DISABLED after
    repeated failures is re-enabled with `status: active`, which resets its failure count.

    Args:
        subscription_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_match (str | Unset):
        body (WebhookUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Problem | WebhookOut
    """

    return sync_detailed(
        subscription_id=subscription_id,
        client=client,
        body=body,
        is_registration=is_registration,
        authorization=authorization,
        if_match=if_match,
    ).parsed


async def asyncio_detailed(
    subscription_id: str,
    *,
    client: AuthenticatedClient,
    body: WebhookUpdate,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_match: str | Unset = UNSET,
) -> Response[Problem | WebhookOut]:
    """Change, pause, resume or re-enable a webhook

     Change the name, URL, events or projects; pause (`status: paused`) or resume (`active`). A webhook
    DISABLED after
    repeated failures is re-enabled with `status: active`, which resets its failure count.

    Args:
        subscription_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_match (str | Unset):
        body (WebhookUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Problem | WebhookOut]
    """

    kwargs = _get_kwargs(
        subscription_id=subscription_id,
        body=body,
        is_registration=is_registration,
        authorization=authorization,
        if_match=if_match,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    subscription_id: str,
    *,
    client: AuthenticatedClient,
    body: WebhookUpdate,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_match: str | Unset = UNSET,
) -> Problem | WebhookOut | None:
    """Change, pause, resume or re-enable a webhook

     Change the name, URL, events or projects; pause (`status: paused`) or resume (`active`). A webhook
    DISABLED after
    repeated failures is re-enabled with `status: active`, which resets its failure count.

    Args:
        subscription_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_match (str | Unset):
        body (WebhookUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Problem | WebhookOut
    """

    return (
        await asyncio_detailed(
            subscription_id=subscription_id,
            client=client,
            body=body,
            is_registration=is_registration,
            authorization=authorization,
            if_match=if_match,
        )
    ).parsed
