# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.problem import Problem
from ...models.task_list_page import TaskListPage
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    *,
    org_id: None | str | Unset = UNSET,
    project_id: None | str | Unset = UNSET,
    limit: int | Unset = 100,
    cursor: None | str | Unset = UNSET,
    sort_by: str | Unset = "title",
    sort_order: str | Unset = "asc",
    include_inaccessible: bool | Unset = False,
    filterstatus: list[str] | None | Unset = UNSET,
    filterpriority: list[str] | None | Unset = UNSET,
    filterassignee: list[str] | None | Unset = UNSET,
    filterproject: list[str] | None | Unset = UNSET,
    filtertags: list[str] | None | Unset = UNSET,
    filterdue_after: None | str | Unset = UNSET,
    filterdue_before: None | str | Unset = UNSET,
    filtercreated_after: None | str | Unset = UNSET,
    filtercreated_before: None | str | Unset = UNSET,
    filteroverdue: None | str | Unset = UNSET,
    filtersearch: None | str | Unset = UNSET,
    filtersearch_fields: None | str | Unset = UNSET,
    filterteam: list[str] | None | Unset = UNSET,
    filtertask_type: list[str] | None | Unset = UNSET,
    section_scope: None | str | Unset = UNSET,
    search: None | str | Unset = UNSET,
    status: None | str | Unset = UNSET,
    unfiled: bool | None | Unset = UNSET,
    offset: int | Unset = 0,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(authorization, Unset):
        headers["authorization"] = authorization

    if not isinstance(if_none_match, Unset):
        headers["If-None-Match"] = if_none_match

    params: dict[str, Any] = {}

    json_org_id: None | str | Unset
    if isinstance(org_id, Unset):
        json_org_id = UNSET
    else:
        json_org_id = org_id
    params["org_id"] = json_org_id

    json_project_id: None | str | Unset
    if isinstance(project_id, Unset):
        json_project_id = UNSET
    else:
        json_project_id = project_id
    params["project_id"] = json_project_id

    params["limit"] = limit

    json_cursor: None | str | Unset
    if isinstance(cursor, Unset):
        json_cursor = UNSET
    else:
        json_cursor = cursor
    params["cursor"] = json_cursor

    params["sort_by"] = sort_by

    params["sort_order"] = sort_order

    params["include_inaccessible"] = include_inaccessible

    json_filterstatus: list[str] | None | Unset
    if isinstance(filterstatus, Unset):
        json_filterstatus = UNSET
    elif isinstance(filterstatus, list):
        json_filterstatus = filterstatus

    else:
        json_filterstatus = filterstatus
    params["filter[status]"] = json_filterstatus

    json_filterpriority: list[str] | None | Unset
    if isinstance(filterpriority, Unset):
        json_filterpriority = UNSET
    elif isinstance(filterpriority, list):
        json_filterpriority = filterpriority

    else:
        json_filterpriority = filterpriority
    params["filter[priority]"] = json_filterpriority

    json_filterassignee: list[str] | None | Unset
    if isinstance(filterassignee, Unset):
        json_filterassignee = UNSET
    elif isinstance(filterassignee, list):
        json_filterassignee = filterassignee

    else:
        json_filterassignee = filterassignee
    params["filter[assignee]"] = json_filterassignee

    json_filterproject: list[str] | None | Unset
    if isinstance(filterproject, Unset):
        json_filterproject = UNSET
    elif isinstance(filterproject, list):
        json_filterproject = filterproject

    else:
        json_filterproject = filterproject
    params["filter[project]"] = json_filterproject

    json_filtertags: list[str] | None | Unset
    if isinstance(filtertags, Unset):
        json_filtertags = UNSET
    elif isinstance(filtertags, list):
        json_filtertags = filtertags

    else:
        json_filtertags = filtertags
    params["filter[tags]"] = json_filtertags

    json_filterdue_after: None | str | Unset
    if isinstance(filterdue_after, Unset):
        json_filterdue_after = UNSET
    else:
        json_filterdue_after = filterdue_after
    params["filter[due_after]"] = json_filterdue_after

    json_filterdue_before: None | str | Unset
    if isinstance(filterdue_before, Unset):
        json_filterdue_before = UNSET
    else:
        json_filterdue_before = filterdue_before
    params["filter[due_before]"] = json_filterdue_before

    json_filtercreated_after: None | str | Unset
    if isinstance(filtercreated_after, Unset):
        json_filtercreated_after = UNSET
    else:
        json_filtercreated_after = filtercreated_after
    params["filter[created_after]"] = json_filtercreated_after

    json_filtercreated_before: None | str | Unset
    if isinstance(filtercreated_before, Unset):
        json_filtercreated_before = UNSET
    else:
        json_filtercreated_before = filtercreated_before
    params["filter[created_before]"] = json_filtercreated_before

    json_filteroverdue: None | str | Unset
    if isinstance(filteroverdue, Unset):
        json_filteroverdue = UNSET
    else:
        json_filteroverdue = filteroverdue
    params["filter[overdue]"] = json_filteroverdue

    json_filtersearch: None | str | Unset
    if isinstance(filtersearch, Unset):
        json_filtersearch = UNSET
    else:
        json_filtersearch = filtersearch
    params["filter[search]"] = json_filtersearch

    json_filtersearch_fields: None | str | Unset
    if isinstance(filtersearch_fields, Unset):
        json_filtersearch_fields = UNSET
    else:
        json_filtersearch_fields = filtersearch_fields
    params["filter[search_fields]"] = json_filtersearch_fields

    json_filterteam: list[str] | None | Unset
    if isinstance(filterteam, Unset):
        json_filterteam = UNSET
    elif isinstance(filterteam, list):
        json_filterteam = filterteam

    else:
        json_filterteam = filterteam
    params["filter[team]"] = json_filterteam

    json_filtertask_type: list[str] | None | Unset
    if isinstance(filtertask_type, Unset):
        json_filtertask_type = UNSET
    elif isinstance(filtertask_type, list):
        json_filtertask_type = filtertask_type

    else:
        json_filtertask_type = filtertask_type
    params["filter[task_type]"] = json_filtertask_type

    json_section_scope: None | str | Unset
    if isinstance(section_scope, Unset):
        json_section_scope = UNSET
    else:
        json_section_scope = section_scope
    params["section_scope"] = json_section_scope

    json_search: None | str | Unset
    if isinstance(search, Unset):
        json_search = UNSET
    else:
        json_search = search
    params["search"] = json_search

    json_status: None | str | Unset
    if isinstance(status, Unset):
        json_status = UNSET
    else:
        json_status = status
    params["status"] = json_status

    json_unfiled: bool | None | Unset
    if isinstance(unfiled, Unset):
        json_unfiled = UNSET
    else:
        json_unfiled = unfiled
    params["unfiled"] = json_unfiled

    params["offset"] = offset

    params["is_registration"] = is_registration

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/v1/tasks",
        "params": params,
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | Problem | TaskListPage | None:
    if response.status_code == 200:
        response_200 = TaskListPage.from_dict(response.json())

        return response_200

    if response.status_code == 304:
        response_304 = cast(Any, None)
        return response_304

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | Problem | TaskListPage]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    org_id: None | str | Unset = UNSET,
    project_id: None | str | Unset = UNSET,
    limit: int | Unset = 100,
    cursor: None | str | Unset = UNSET,
    sort_by: str | Unset = "title",
    sort_order: str | Unset = "asc",
    include_inaccessible: bool | Unset = False,
    filterstatus: list[str] | None | Unset = UNSET,
    filterpriority: list[str] | None | Unset = UNSET,
    filterassignee: list[str] | None | Unset = UNSET,
    filterproject: list[str] | None | Unset = UNSET,
    filtertags: list[str] | None | Unset = UNSET,
    filterdue_after: None | str | Unset = UNSET,
    filterdue_before: None | str | Unset = UNSET,
    filtercreated_after: None | str | Unset = UNSET,
    filtercreated_before: None | str | Unset = UNSET,
    filteroverdue: None | str | Unset = UNSET,
    filtersearch: None | str | Unset = UNSET,
    filtersearch_fields: None | str | Unset = UNSET,
    filterteam: list[str] | None | Unset = UNSET,
    filtertask_type: list[str] | None | Unset = UNSET,
    section_scope: None | str | Unset = UNSET,
    search: None | str | Unset = UNSET,
    status: None | str | Unset = UNSET,
    unfiled: bool | None | Unset = UNSET,
    offset: int | Unset = 0,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Response[Any | Problem | TaskListPage]:
    """List / search tasks (the filter grammar; `filter[search]` is search)

     List the tasks the caller may see, one page at a time (task 1.5).

    **Envelope:** `{"data": [TaskCardView...], "next_cursor": "<opaque>" | null}`.
    Pass `next_cursor` back as `cursor` to get the next page; `null` means the
    database returned fewer than `limit` rows, i.e. the end. The cursor is
    minted from the last row the **database** returned, before restricted rows
    are dropped, so a page may be `data: []` with a non-null `next_cursor` —
    keep walking until the cursor is null. A cursor is bound to the filters,
    sort and scope it was minted for; reusing it with a different query → 400.

    **Scope / visibility (task 2.2):** `project_id` → the caller must be able to
    read the project (public, or member, or org admin); otherwise `org_id` is
    required → org membership required, and rows come only from projects the
    caller may read plus unfiled tasks (private projects the caller is not in
    never appear). Restricted tasks are dropped (or flagged with
    `include_inaccessible=true`) after the query.

    **Filters:** repeated `filter[...]` params; comma-separated values are OR
    within a key, keys are AND-ed. Unknown key, bad date, non-boolean `overdue`,
    unknown status/priority → 400 naming the offender.

    **Sort:** `sort_by` whitelist (`task_id, title, status, priority, due_date,
    start_date, created_at, assignee, project_id, priority_rank, status_rank,
    task_type`),
    `sort_order` asc|desc, tie broken by `task_id`; nullable columns sort nulls
    last. `status` / `priority` are aliases of `status_rank` / `priority_rank`
    (1.9b): the client's ranking (critical>high>medium>low>none,
    in_progress>not_started>blocked>completed), never the enum declaration
    order. Frontend field names map as `id→task_id`, `name→title`,
    `targetDate→due_date`, `owner→assignee`, `createdDate→created_at`.
    `task_type` (3.3) sorts in enum order (task · bug · goal · agent).

    **Type (3.3):** `filter[task_type]` = one or more of `task, bug, agent` (6.12: `goal` → 400)
    (OR within the key). A type is a label, never a permission: the filter runs
    over the rows the caller could already see. Every row carries `task_type`
    (`task` for rows that predate the column).

    **Search (1.9b):** `filter[search]` matches title, description, task id and
    tags (the catalog's searchable text); `filter[search_fields]=title` keeps the
    title-only match.

    **Sections (1.7):** `section_scope=user:me` | `project:<id>` | `team:<id>` adds
    `section_id` and `section_position` to every row for that one scope (`null` when
    the task has no section there). Annotated in Python after the query; the envelope
    is otherwise unchanged.

    **`section_scope=own` (6.1b):** there is no one scope — each row is annotated at
    **its own holder's**: a row with a `project_id` at `project:<that id>`, a row
    without one at `team:<its team_id>` (a task filed under a team and no project).
    A row with **neither** has no holder and is annotated as unsectioned rather than
    guessed at. It is still one `task_sections` query for the page, and it widens
    nothing: the rows are the ones 2.2's visibility filter and the restriction pass
    already returned, each labelled with the section it sits in where it lives. This
    is what a team tree reads with `filter[team]=<id>`. `own` is accepted **here
    only** — group-counts and saved views still reject it (a count needs one scope).

    Args:
        org_id (None | str | Unset): Organization scope; required unless project_id is given.
            Membership is checked; only projects the caller may read (public, member-of, or all for
            org admins) plus unfiled tasks are listed.
        project_id (None | str | Unset): Project scope; the caller must be able to read the
            project (public, or member, or org admin).
        limit (int | Unset): Page size, default 100; silently clamped to 1000. Default: 100.
        cursor (None | str | Unset): Opaque token from the previous page's `next_cursor`. Only
            ever echo it back; `offset` is ignored when it is given.
        sort_by (str | Unset): One of: task_id, title, status, priority, due_date, start_date,
            created_at, assignee, project_id, priority_rank, status_rank, task_type (400 otherwise).
            Default: 'title'.
        sort_order (str | Unset): asc or desc (400 otherwise). Default: 'asc'.
        include_inaccessible (bool | Unset): If true, include tasks the current user cannot access
            due to `restricted_to`, marked with has_access=False. If false (default), those tasks are
            not returned. Membership is always required: rows only come from the project / org the
            caller belongs to. Default: False.
        filterstatus (list[str] | None | Unset): Task status(es), comma-separated or repeated.
        filterpriority (list[str] | None | Unset): Priority(ies), comma-separated or repeated.
        filterassignee (list[str] | None | Unset): Usernames, or `me` for the caller.
        filterproject (list[str] | None | Unset): Project ids, or `__unfiled__` for tasks without
            a project (mixable).
        filtertags (list[str] | None | Unset): Tasks carrying any of these tags.
        filterdue_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filterdue_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filteroverdue (None | str | Unset): `true` → due before today and not completed (the
            frontend's isTaskOverdue rule).
        filtersearch (None | str | Unset): Case-insensitive substring of title, description, task
            id or any tag (1.9b); `%`, `_`, `*`, `,`, `(` are matched literally.
        filtersearch_fields (None | str | Unset): `all` (default) or `title` to keep the pre-1.9b
            title-only match.
        filterteam (list[str] | None | Unset): Team ids, or `__none__` for tasks without a team
            (2.6a; mixable).
        filtertask_type (list[str] | None | Unset): One or more of `task, bug, agent` (3.3),
            comma-separated or repeated; unknown value → 400 (6.12: `goal` is retired).
        section_scope (None | str | Unset): `user:me`, `project:<id>` (task 1.7), `team:<id>`
            (2.6a) or `own` (6.1b: each row at its OWN holder's scope). Unknown scope → 400.
        search (None | str | Unset): Deprecated alias of filter[search].
        status (None | str | Unset): Deprecated alias of filter[status].
        unfiled (bool | None | Unset): Deprecated alias of filter[project]=__unfiled__ (ignored
            when project_id is given).
        offset (int | Unset): Deprecated; use `cursor`. Ignored when a cursor is given. Default:
            0.
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Problem | TaskListPage]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        project_id=project_id,
        limit=limit,
        cursor=cursor,
        sort_by=sort_by,
        sort_order=sort_order,
        include_inaccessible=include_inaccessible,
        filterstatus=filterstatus,
        filterpriority=filterpriority,
        filterassignee=filterassignee,
        filterproject=filterproject,
        filtertags=filtertags,
        filterdue_after=filterdue_after,
        filterdue_before=filterdue_before,
        filtercreated_after=filtercreated_after,
        filtercreated_before=filtercreated_before,
        filteroverdue=filteroverdue,
        filtersearch=filtersearch,
        filtersearch_fields=filtersearch_fields,
        filterteam=filterteam,
        filtertask_type=filtertask_type,
        section_scope=section_scope,
        search=search,
        status=status,
        unfiled=unfiled,
        offset=offset,
        is_registration=is_registration,
        authorization=authorization,
        if_none_match=if_none_match,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    org_id: None | str | Unset = UNSET,
    project_id: None | str | Unset = UNSET,
    limit: int | Unset = 100,
    cursor: None | str | Unset = UNSET,
    sort_by: str | Unset = "title",
    sort_order: str | Unset = "asc",
    include_inaccessible: bool | Unset = False,
    filterstatus: list[str] | None | Unset = UNSET,
    filterpriority: list[str] | None | Unset = UNSET,
    filterassignee: list[str] | None | Unset = UNSET,
    filterproject: list[str] | None | Unset = UNSET,
    filtertags: list[str] | None | Unset = UNSET,
    filterdue_after: None | str | Unset = UNSET,
    filterdue_before: None | str | Unset = UNSET,
    filtercreated_after: None | str | Unset = UNSET,
    filtercreated_before: None | str | Unset = UNSET,
    filteroverdue: None | str | Unset = UNSET,
    filtersearch: None | str | Unset = UNSET,
    filtersearch_fields: None | str | Unset = UNSET,
    filterteam: list[str] | None | Unset = UNSET,
    filtertask_type: list[str] | None | Unset = UNSET,
    section_scope: None | str | Unset = UNSET,
    search: None | str | Unset = UNSET,
    status: None | str | Unset = UNSET,
    unfiled: bool | None | Unset = UNSET,
    offset: int | Unset = 0,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Any | Problem | TaskListPage | None:
    """List / search tasks (the filter grammar; `filter[search]` is search)

     List the tasks the caller may see, one page at a time (task 1.5).

    **Envelope:** `{"data": [TaskCardView...], "next_cursor": "<opaque>" | null}`.
    Pass `next_cursor` back as `cursor` to get the next page; `null` means the
    database returned fewer than `limit` rows, i.e. the end. The cursor is
    minted from the last row the **database** returned, before restricted rows
    are dropped, so a page may be `data: []` with a non-null `next_cursor` —
    keep walking until the cursor is null. A cursor is bound to the filters,
    sort and scope it was minted for; reusing it with a different query → 400.

    **Scope / visibility (task 2.2):** `project_id` → the caller must be able to
    read the project (public, or member, or org admin); otherwise `org_id` is
    required → org membership required, and rows come only from projects the
    caller may read plus unfiled tasks (private projects the caller is not in
    never appear). Restricted tasks are dropped (or flagged with
    `include_inaccessible=true`) after the query.

    **Filters:** repeated `filter[...]` params; comma-separated values are OR
    within a key, keys are AND-ed. Unknown key, bad date, non-boolean `overdue`,
    unknown status/priority → 400 naming the offender.

    **Sort:** `sort_by` whitelist (`task_id, title, status, priority, due_date,
    start_date, created_at, assignee, project_id, priority_rank, status_rank,
    task_type`),
    `sort_order` asc|desc, tie broken by `task_id`; nullable columns sort nulls
    last. `status` / `priority` are aliases of `status_rank` / `priority_rank`
    (1.9b): the client's ranking (critical>high>medium>low>none,
    in_progress>not_started>blocked>completed), never the enum declaration
    order. Frontend field names map as `id→task_id`, `name→title`,
    `targetDate→due_date`, `owner→assignee`, `createdDate→created_at`.
    `task_type` (3.3) sorts in enum order (task · bug · goal · agent).

    **Type (3.3):** `filter[task_type]` = one or more of `task, bug, agent` (6.12: `goal` → 400)
    (OR within the key). A type is a label, never a permission: the filter runs
    over the rows the caller could already see. Every row carries `task_type`
    (`task` for rows that predate the column).

    **Search (1.9b):** `filter[search]` matches title, description, task id and
    tags (the catalog's searchable text); `filter[search_fields]=title` keeps the
    title-only match.

    **Sections (1.7):** `section_scope=user:me` | `project:<id>` | `team:<id>` adds
    `section_id` and `section_position` to every row for that one scope (`null` when
    the task has no section there). Annotated in Python after the query; the envelope
    is otherwise unchanged.

    **`section_scope=own` (6.1b):** there is no one scope — each row is annotated at
    **its own holder's**: a row with a `project_id` at `project:<that id>`, a row
    without one at `team:<its team_id>` (a task filed under a team and no project).
    A row with **neither** has no holder and is annotated as unsectioned rather than
    guessed at. It is still one `task_sections` query for the page, and it widens
    nothing: the rows are the ones 2.2's visibility filter and the restriction pass
    already returned, each labelled with the section it sits in where it lives. This
    is what a team tree reads with `filter[team]=<id>`. `own` is accepted **here
    only** — group-counts and saved views still reject it (a count needs one scope).

    Args:
        org_id (None | str | Unset): Organization scope; required unless project_id is given.
            Membership is checked; only projects the caller may read (public, member-of, or all for
            org admins) plus unfiled tasks are listed.
        project_id (None | str | Unset): Project scope; the caller must be able to read the
            project (public, or member, or org admin).
        limit (int | Unset): Page size, default 100; silently clamped to 1000. Default: 100.
        cursor (None | str | Unset): Opaque token from the previous page's `next_cursor`. Only
            ever echo it back; `offset` is ignored when it is given.
        sort_by (str | Unset): One of: task_id, title, status, priority, due_date, start_date,
            created_at, assignee, project_id, priority_rank, status_rank, task_type (400 otherwise).
            Default: 'title'.
        sort_order (str | Unset): asc or desc (400 otherwise). Default: 'asc'.
        include_inaccessible (bool | Unset): If true, include tasks the current user cannot access
            due to `restricted_to`, marked with has_access=False. If false (default), those tasks are
            not returned. Membership is always required: rows only come from the project / org the
            caller belongs to. Default: False.
        filterstatus (list[str] | None | Unset): Task status(es), comma-separated or repeated.
        filterpriority (list[str] | None | Unset): Priority(ies), comma-separated or repeated.
        filterassignee (list[str] | None | Unset): Usernames, or `me` for the caller.
        filterproject (list[str] | None | Unset): Project ids, or `__unfiled__` for tasks without
            a project (mixable).
        filtertags (list[str] | None | Unset): Tasks carrying any of these tags.
        filterdue_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filterdue_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filteroverdue (None | str | Unset): `true` → due before today and not completed (the
            frontend's isTaskOverdue rule).
        filtersearch (None | str | Unset): Case-insensitive substring of title, description, task
            id or any tag (1.9b); `%`, `_`, `*`, `,`, `(` are matched literally.
        filtersearch_fields (None | str | Unset): `all` (default) or `title` to keep the pre-1.9b
            title-only match.
        filterteam (list[str] | None | Unset): Team ids, or `__none__` for tasks without a team
            (2.6a; mixable).
        filtertask_type (list[str] | None | Unset): One or more of `task, bug, agent` (3.3),
            comma-separated or repeated; unknown value → 400 (6.12: `goal` is retired).
        section_scope (None | str | Unset): `user:me`, `project:<id>` (task 1.7), `team:<id>`
            (2.6a) or `own` (6.1b: each row at its OWN holder's scope). Unknown scope → 400.
        search (None | str | Unset): Deprecated alias of filter[search].
        status (None | str | Unset): Deprecated alias of filter[status].
        unfiled (bool | None | Unset): Deprecated alias of filter[project]=__unfiled__ (ignored
            when project_id is given).
        offset (int | Unset): Deprecated; use `cursor`. Ignored when a cursor is given. Default:
            0.
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Problem | TaskListPage
    """

    return sync_detailed(
        client=client,
        org_id=org_id,
        project_id=project_id,
        limit=limit,
        cursor=cursor,
        sort_by=sort_by,
        sort_order=sort_order,
        include_inaccessible=include_inaccessible,
        filterstatus=filterstatus,
        filterpriority=filterpriority,
        filterassignee=filterassignee,
        filterproject=filterproject,
        filtertags=filtertags,
        filterdue_after=filterdue_after,
        filterdue_before=filterdue_before,
        filtercreated_after=filtercreated_after,
        filtercreated_before=filtercreated_before,
        filteroverdue=filteroverdue,
        filtersearch=filtersearch,
        filtersearch_fields=filtersearch_fields,
        filterteam=filterteam,
        filtertask_type=filtertask_type,
        section_scope=section_scope,
        search=search,
        status=status,
        unfiled=unfiled,
        offset=offset,
        is_registration=is_registration,
        authorization=authorization,
        if_none_match=if_none_match,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    org_id: None | str | Unset = UNSET,
    project_id: None | str | Unset = UNSET,
    limit: int | Unset = 100,
    cursor: None | str | Unset = UNSET,
    sort_by: str | Unset = "title",
    sort_order: str | Unset = "asc",
    include_inaccessible: bool | Unset = False,
    filterstatus: list[str] | None | Unset = UNSET,
    filterpriority: list[str] | None | Unset = UNSET,
    filterassignee: list[str] | None | Unset = UNSET,
    filterproject: list[str] | None | Unset = UNSET,
    filtertags: list[str] | None | Unset = UNSET,
    filterdue_after: None | str | Unset = UNSET,
    filterdue_before: None | str | Unset = UNSET,
    filtercreated_after: None | str | Unset = UNSET,
    filtercreated_before: None | str | Unset = UNSET,
    filteroverdue: None | str | Unset = UNSET,
    filtersearch: None | str | Unset = UNSET,
    filtersearch_fields: None | str | Unset = UNSET,
    filterteam: list[str] | None | Unset = UNSET,
    filtertask_type: list[str] | None | Unset = UNSET,
    section_scope: None | str | Unset = UNSET,
    search: None | str | Unset = UNSET,
    status: None | str | Unset = UNSET,
    unfiled: bool | None | Unset = UNSET,
    offset: int | Unset = 0,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Response[Any | Problem | TaskListPage]:
    """List / search tasks (the filter grammar; `filter[search]` is search)

     List the tasks the caller may see, one page at a time (task 1.5).

    **Envelope:** `{"data": [TaskCardView...], "next_cursor": "<opaque>" | null}`.
    Pass `next_cursor` back as `cursor` to get the next page; `null` means the
    database returned fewer than `limit` rows, i.e. the end. The cursor is
    minted from the last row the **database** returned, before restricted rows
    are dropped, so a page may be `data: []` with a non-null `next_cursor` —
    keep walking until the cursor is null. A cursor is bound to the filters,
    sort and scope it was minted for; reusing it with a different query → 400.

    **Scope / visibility (task 2.2):** `project_id` → the caller must be able to
    read the project (public, or member, or org admin); otherwise `org_id` is
    required → org membership required, and rows come only from projects the
    caller may read plus unfiled tasks (private projects the caller is not in
    never appear). Restricted tasks are dropped (or flagged with
    `include_inaccessible=true`) after the query.

    **Filters:** repeated `filter[...]` params; comma-separated values are OR
    within a key, keys are AND-ed. Unknown key, bad date, non-boolean `overdue`,
    unknown status/priority → 400 naming the offender.

    **Sort:** `sort_by` whitelist (`task_id, title, status, priority, due_date,
    start_date, created_at, assignee, project_id, priority_rank, status_rank,
    task_type`),
    `sort_order` asc|desc, tie broken by `task_id`; nullable columns sort nulls
    last. `status` / `priority` are aliases of `status_rank` / `priority_rank`
    (1.9b): the client's ranking (critical>high>medium>low>none,
    in_progress>not_started>blocked>completed), never the enum declaration
    order. Frontend field names map as `id→task_id`, `name→title`,
    `targetDate→due_date`, `owner→assignee`, `createdDate→created_at`.
    `task_type` (3.3) sorts in enum order (task · bug · goal · agent).

    **Type (3.3):** `filter[task_type]` = one or more of `task, bug, agent` (6.12: `goal` → 400)
    (OR within the key). A type is a label, never a permission: the filter runs
    over the rows the caller could already see. Every row carries `task_type`
    (`task` for rows that predate the column).

    **Search (1.9b):** `filter[search]` matches title, description, task id and
    tags (the catalog's searchable text); `filter[search_fields]=title` keeps the
    title-only match.

    **Sections (1.7):** `section_scope=user:me` | `project:<id>` | `team:<id>` adds
    `section_id` and `section_position` to every row for that one scope (`null` when
    the task has no section there). Annotated in Python after the query; the envelope
    is otherwise unchanged.

    **`section_scope=own` (6.1b):** there is no one scope — each row is annotated at
    **its own holder's**: a row with a `project_id` at `project:<that id>`, a row
    without one at `team:<its team_id>` (a task filed under a team and no project).
    A row with **neither** has no holder and is annotated as unsectioned rather than
    guessed at. It is still one `task_sections` query for the page, and it widens
    nothing: the rows are the ones 2.2's visibility filter and the restriction pass
    already returned, each labelled with the section it sits in where it lives. This
    is what a team tree reads with `filter[team]=<id>`. `own` is accepted **here
    only** — group-counts and saved views still reject it (a count needs one scope).

    Args:
        org_id (None | str | Unset): Organization scope; required unless project_id is given.
            Membership is checked; only projects the caller may read (public, member-of, or all for
            org admins) plus unfiled tasks are listed.
        project_id (None | str | Unset): Project scope; the caller must be able to read the
            project (public, or member, or org admin).
        limit (int | Unset): Page size, default 100; silently clamped to 1000. Default: 100.
        cursor (None | str | Unset): Opaque token from the previous page's `next_cursor`. Only
            ever echo it back; `offset` is ignored when it is given.
        sort_by (str | Unset): One of: task_id, title, status, priority, due_date, start_date,
            created_at, assignee, project_id, priority_rank, status_rank, task_type (400 otherwise).
            Default: 'title'.
        sort_order (str | Unset): asc or desc (400 otherwise). Default: 'asc'.
        include_inaccessible (bool | Unset): If true, include tasks the current user cannot access
            due to `restricted_to`, marked with has_access=False. If false (default), those tasks are
            not returned. Membership is always required: rows only come from the project / org the
            caller belongs to. Default: False.
        filterstatus (list[str] | None | Unset): Task status(es), comma-separated or repeated.
        filterpriority (list[str] | None | Unset): Priority(ies), comma-separated or repeated.
        filterassignee (list[str] | None | Unset): Usernames, or `me` for the caller.
        filterproject (list[str] | None | Unset): Project ids, or `__unfiled__` for tasks without
            a project (mixable).
        filtertags (list[str] | None | Unset): Tasks carrying any of these tags.
        filterdue_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filterdue_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filteroverdue (None | str | Unset): `true` → due before today and not completed (the
            frontend's isTaskOverdue rule).
        filtersearch (None | str | Unset): Case-insensitive substring of title, description, task
            id or any tag (1.9b); `%`, `_`, `*`, `,`, `(` are matched literally.
        filtersearch_fields (None | str | Unset): `all` (default) or `title` to keep the pre-1.9b
            title-only match.
        filterteam (list[str] | None | Unset): Team ids, or `__none__` for tasks without a team
            (2.6a; mixable).
        filtertask_type (list[str] | None | Unset): One or more of `task, bug, agent` (3.3),
            comma-separated or repeated; unknown value → 400 (6.12: `goal` is retired).
        section_scope (None | str | Unset): `user:me`, `project:<id>` (task 1.7), `team:<id>`
            (2.6a) or `own` (6.1b: each row at its OWN holder's scope). Unknown scope → 400.
        search (None | str | Unset): Deprecated alias of filter[search].
        status (None | str | Unset): Deprecated alias of filter[status].
        unfiled (bool | None | Unset): Deprecated alias of filter[project]=__unfiled__ (ignored
            when project_id is given).
        offset (int | Unset): Deprecated; use `cursor`. Ignored when a cursor is given. Default:
            0.
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Problem | TaskListPage]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        project_id=project_id,
        limit=limit,
        cursor=cursor,
        sort_by=sort_by,
        sort_order=sort_order,
        include_inaccessible=include_inaccessible,
        filterstatus=filterstatus,
        filterpriority=filterpriority,
        filterassignee=filterassignee,
        filterproject=filterproject,
        filtertags=filtertags,
        filterdue_after=filterdue_after,
        filterdue_before=filterdue_before,
        filtercreated_after=filtercreated_after,
        filtercreated_before=filtercreated_before,
        filteroverdue=filteroverdue,
        filtersearch=filtersearch,
        filtersearch_fields=filtersearch_fields,
        filterteam=filterteam,
        filtertask_type=filtertask_type,
        section_scope=section_scope,
        search=search,
        status=status,
        unfiled=unfiled,
        offset=offset,
        is_registration=is_registration,
        authorization=authorization,
        if_none_match=if_none_match,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    org_id: None | str | Unset = UNSET,
    project_id: None | str | Unset = UNSET,
    limit: int | Unset = 100,
    cursor: None | str | Unset = UNSET,
    sort_by: str | Unset = "title",
    sort_order: str | Unset = "asc",
    include_inaccessible: bool | Unset = False,
    filterstatus: list[str] | None | Unset = UNSET,
    filterpriority: list[str] | None | Unset = UNSET,
    filterassignee: list[str] | None | Unset = UNSET,
    filterproject: list[str] | None | Unset = UNSET,
    filtertags: list[str] | None | Unset = UNSET,
    filterdue_after: None | str | Unset = UNSET,
    filterdue_before: None | str | Unset = UNSET,
    filtercreated_after: None | str | Unset = UNSET,
    filtercreated_before: None | str | Unset = UNSET,
    filteroverdue: None | str | Unset = UNSET,
    filtersearch: None | str | Unset = UNSET,
    filtersearch_fields: None | str | Unset = UNSET,
    filterteam: list[str] | None | Unset = UNSET,
    filtertask_type: list[str] | None | Unset = UNSET,
    section_scope: None | str | Unset = UNSET,
    search: None | str | Unset = UNSET,
    status: None | str | Unset = UNSET,
    unfiled: bool | None | Unset = UNSET,
    offset: int | Unset = 0,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Any | Problem | TaskListPage | None:
    """List / search tasks (the filter grammar; `filter[search]` is search)

     List the tasks the caller may see, one page at a time (task 1.5).

    **Envelope:** `{"data": [TaskCardView...], "next_cursor": "<opaque>" | null}`.
    Pass `next_cursor` back as `cursor` to get the next page; `null` means the
    database returned fewer than `limit` rows, i.e. the end. The cursor is
    minted from the last row the **database** returned, before restricted rows
    are dropped, so a page may be `data: []` with a non-null `next_cursor` —
    keep walking until the cursor is null. A cursor is bound to the filters,
    sort and scope it was minted for; reusing it with a different query → 400.

    **Scope / visibility (task 2.2):** `project_id` → the caller must be able to
    read the project (public, or member, or org admin); otherwise `org_id` is
    required → org membership required, and rows come only from projects the
    caller may read plus unfiled tasks (private projects the caller is not in
    never appear). Restricted tasks are dropped (or flagged with
    `include_inaccessible=true`) after the query.

    **Filters:** repeated `filter[...]` params; comma-separated values are OR
    within a key, keys are AND-ed. Unknown key, bad date, non-boolean `overdue`,
    unknown status/priority → 400 naming the offender.

    **Sort:** `sort_by` whitelist (`task_id, title, status, priority, due_date,
    start_date, created_at, assignee, project_id, priority_rank, status_rank,
    task_type`),
    `sort_order` asc|desc, tie broken by `task_id`; nullable columns sort nulls
    last. `status` / `priority` are aliases of `status_rank` / `priority_rank`
    (1.9b): the client's ranking (critical>high>medium>low>none,
    in_progress>not_started>blocked>completed), never the enum declaration
    order. Frontend field names map as `id→task_id`, `name→title`,
    `targetDate→due_date`, `owner→assignee`, `createdDate→created_at`.
    `task_type` (3.3) sorts in enum order (task · bug · goal · agent).

    **Type (3.3):** `filter[task_type]` = one or more of `task, bug, agent` (6.12: `goal` → 400)
    (OR within the key). A type is a label, never a permission: the filter runs
    over the rows the caller could already see. Every row carries `task_type`
    (`task` for rows that predate the column).

    **Search (1.9b):** `filter[search]` matches title, description, task id and
    tags (the catalog's searchable text); `filter[search_fields]=title` keeps the
    title-only match.

    **Sections (1.7):** `section_scope=user:me` | `project:<id>` | `team:<id>` adds
    `section_id` and `section_position` to every row for that one scope (`null` when
    the task has no section there). Annotated in Python after the query; the envelope
    is otherwise unchanged.

    **`section_scope=own` (6.1b):** there is no one scope — each row is annotated at
    **its own holder's**: a row with a `project_id` at `project:<that id>`, a row
    without one at `team:<its team_id>` (a task filed under a team and no project).
    A row with **neither** has no holder and is annotated as unsectioned rather than
    guessed at. It is still one `task_sections` query for the page, and it widens
    nothing: the rows are the ones 2.2's visibility filter and the restriction pass
    already returned, each labelled with the section it sits in where it lives. This
    is what a team tree reads with `filter[team]=<id>`. `own` is accepted **here
    only** — group-counts and saved views still reject it (a count needs one scope).

    Args:
        org_id (None | str | Unset): Organization scope; required unless project_id is given.
            Membership is checked; only projects the caller may read (public, member-of, or all for
            org admins) plus unfiled tasks are listed.
        project_id (None | str | Unset): Project scope; the caller must be able to read the
            project (public, or member, or org admin).
        limit (int | Unset): Page size, default 100; silently clamped to 1000. Default: 100.
        cursor (None | str | Unset): Opaque token from the previous page's `next_cursor`. Only
            ever echo it back; `offset` is ignored when it is given.
        sort_by (str | Unset): One of: task_id, title, status, priority, due_date, start_date,
            created_at, assignee, project_id, priority_rank, status_rank, task_type (400 otherwise).
            Default: 'title'.
        sort_order (str | Unset): asc or desc (400 otherwise). Default: 'asc'.
        include_inaccessible (bool | Unset): If true, include tasks the current user cannot access
            due to `restricted_to`, marked with has_access=False. If false (default), those tasks are
            not returned. Membership is always required: rows only come from the project / org the
            caller belongs to. Default: False.
        filterstatus (list[str] | None | Unset): Task status(es), comma-separated or repeated.
        filterpriority (list[str] | None | Unset): Priority(ies), comma-separated or repeated.
        filterassignee (list[str] | None | Unset): Usernames, or `me` for the caller.
        filterproject (list[str] | None | Unset): Project ids, or `__unfiled__` for tasks without
            a project (mixable).
        filtertags (list[str] | None | Unset): Tasks carrying any of these tags.
        filterdue_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filterdue_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_after (None | str | Unset): YYYY-MM-DD, inclusive.
        filtercreated_before (None | str | Unset): YYYY-MM-DD, inclusive.
        filteroverdue (None | str | Unset): `true` → due before today and not completed (the
            frontend's isTaskOverdue rule).
        filtersearch (None | str | Unset): Case-insensitive substring of title, description, task
            id or any tag (1.9b); `%`, `_`, `*`, `,`, `(` are matched literally.
        filtersearch_fields (None | str | Unset): `all` (default) or `title` to keep the pre-1.9b
            title-only match.
        filterteam (list[str] | None | Unset): Team ids, or `__none__` for tasks without a team
            (2.6a; mixable).
        filtertask_type (list[str] | None | Unset): One or more of `task, bug, agent` (3.3),
            comma-separated or repeated; unknown value → 400 (6.12: `goal` is retired).
        section_scope (None | str | Unset): `user:me`, `project:<id>` (task 1.7), `team:<id>`
            (2.6a) or `own` (6.1b: each row at its OWN holder's scope). Unknown scope → 400.
        search (None | str | Unset): Deprecated alias of filter[search].
        status (None | str | Unset): Deprecated alias of filter[status].
        unfiled (bool | None | Unset): Deprecated alias of filter[project]=__unfiled__ (ignored
            when project_id is given).
        offset (int | Unset): Deprecated; use `cursor`. Ignored when a cursor is given. Default:
            0.
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Problem | TaskListPage
    """

    return (
        await asyncio_detailed(
            client=client,
            org_id=org_id,
            project_id=project_id,
            limit=limit,
            cursor=cursor,
            sort_by=sort_by,
            sort_order=sort_order,
            include_inaccessible=include_inaccessible,
            filterstatus=filterstatus,
            filterpriority=filterpriority,
            filterassignee=filterassignee,
            filterproject=filterproject,
            filtertags=filtertags,
            filterdue_after=filterdue_after,
            filterdue_before=filterdue_before,
            filtercreated_after=filtercreated_after,
            filtercreated_before=filtercreated_before,
            filteroverdue=filteroverdue,
            filtersearch=filtersearch,
            filtersearch_fields=filtersearch_fields,
            filterteam=filterteam,
            filtertask_type=filtertask_type,
            section_scope=section_scope,
            search=search,
            status=status,
            unfiled=unfiled,
            offset=offset,
            is_registration=is_registration,
            authorization=authorization,
            if_none_match=if_none_match,
        )
    ).parsed
