# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.designation import Designation
from ...models.designation_update import DesignationUpdate
from ...models.problem import Problem
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    designation_id: str,
    *,
    body: DesignationUpdate,
    org_id: str,
    if_match: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(if_match, Unset):
        headers["If-Match"] = if_match

    params: dict[str, Any] = {}

    params["org_id"] = org_id

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "put",
        "url": "/v1/designations/{designation_id}".format(
            designation_id=quote(str(designation_id), safe=""),
        ),
        "params": params,
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Designation | Problem | None:
    if response.status_code == 200:
        response_200 = Designation.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Designation | Problem]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    designation_id: str,
    *,
    client: AuthenticatedClient,
    body: DesignationUpdate,
    org_id: str,
    if_match: str | Unset = UNSET,
) -> Response[Designation | Problem]:
    """Update a designation (PUT)

     **Use PATCH** (JSON merge-patch, the documented verb). PUT is the same partial update, kept for the
    TasksMate app until the 4.5 SDK.


    Args:
        designation_id (str):
        org_id (str):
        if_match (str | Unset):
        body (DesignationUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Designation | Problem]
    """

    kwargs = _get_kwargs(
        designation_id=designation_id,
        body=body,
        org_id=org_id,
        if_match=if_match,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    designation_id: str,
    *,
    client: AuthenticatedClient,
    body: DesignationUpdate,
    org_id: str,
    if_match: str | Unset = UNSET,
) -> Designation | Problem | None:
    """Update a designation (PUT)

     **Use PATCH** (JSON merge-patch, the documented verb). PUT is the same partial update, kept for the
    TasksMate app until the 4.5 SDK.


    Args:
        designation_id (str):
        org_id (str):
        if_match (str | Unset):
        body (DesignationUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Designation | Problem
    """

    return sync_detailed(
        designation_id=designation_id,
        client=client,
        body=body,
        org_id=org_id,
        if_match=if_match,
    ).parsed


async def asyncio_detailed(
    designation_id: str,
    *,
    client: AuthenticatedClient,
    body: DesignationUpdate,
    org_id: str,
    if_match: str | Unset = UNSET,
) -> Response[Designation | Problem]:
    """Update a designation (PUT)

     **Use PATCH** (JSON merge-patch, the documented verb). PUT is the same partial update, kept for the
    TasksMate app until the 4.5 SDK.


    Args:
        designation_id (str):
        org_id (str):
        if_match (str | Unset):
        body (DesignationUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Designation | Problem]
    """

    kwargs = _get_kwargs(
        designation_id=designation_id,
        body=body,
        org_id=org_id,
        if_match=if_match,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    designation_id: str,
    *,
    client: AuthenticatedClient,
    body: DesignationUpdate,
    org_id: str,
    if_match: str | Unset = UNSET,
) -> Designation | Problem | None:
    """Update a designation (PUT)

     **Use PATCH** (JSON merge-patch, the documented verb). PUT is the same partial update, kept for the
    TasksMate app until the 4.5 SDK.


    Args:
        designation_id (str):
        org_id (str):
        if_match (str | Unset):
        body (DesignationUpdate):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Designation | Problem
    """

    return (
        await asyncio_detailed(
            designation_id=designation_id,
            client=client,
            body=body,
            org_id=org_id,
            if_match=if_match,
        )
    ).parsed
