# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.org_milestones_out import OrgMilestonesOut
from ...models.problem import Problem
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    *,
    org_id: str,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    filterproject: list[str] | None | Unset = UNSET,
    filterstatus: list[str] | None | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(if_none_match, Unset):
        headers["If-None-Match"] = if_none_match

    params: dict[str, Any] = {}

    params["org_id"] = org_id

    json_sort_by: None | str | Unset
    if isinstance(sort_by, Unset):
        json_sort_by = UNSET
    else:
        json_sort_by = sort_by
    params["sort_by"] = json_sort_by

    params["sort_order"] = sort_order

    json_filterproject: list[str] | None | Unset
    if isinstance(filterproject, Unset):
        json_filterproject = UNSET
    elif isinstance(filterproject, list):
        json_filterproject = filterproject

    else:
        json_filterproject = filterproject
    params["filter[project]"] = json_filterproject

    json_filterstatus: list[str] | None | Unset
    if isinstance(filterstatus, Unset):
        json_filterstatus = UNSET
    elif isinstance(filterstatus, list):
        json_filterstatus = filterstatus

    else:
        json_filterstatus = filterstatus
    params["filter[status]"] = json_filterstatus

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/v1/milestones",
        "params": params,
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | OrgMilestonesOut | Problem | None:
    if response.status_code == 200:
        response_200 = OrgMilestonesOut.from_dict(response.json())

        return response_200

    if response.status_code == 304:
        response_304 = cast(Any, None)
        return response_304

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | OrgMilestonesOut | Problem]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    org_id: str,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    filterproject: list[str] | None | Unset = UNSET,
    filterstatus: list[str] | None | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Response[Any | OrgMilestonesOut | Problem]:
    """Every milestone you can read in an organization, grouped by project

     Every live milestone in the projects you can read, grouped by project - the shape of `GET
    /v1/goals`. Each milestone carries its task roll-up and `project_name`; each group
    `milestones_tasks_total` / `milestones_tasks_completed`. Not paginated.

    - **Who sees what:** the projects you can read (a guest: only the projects they are a member of).
    403 when you are not a member of the organization.
    - **Order:** the organization's project order, then each project's milestones by position.
    - **Filters:** `filter[project]` (project ids) and `filter[status]` (`open` / `closed`); the sums
    count what is returned.
    - **Sort:** `sort_by=project_name` orders the projects; any other key orders each project's
    milestones.

    Args:
        org_id (str): Organization scope; the caller must be a member (a guest sees only its
            projects' milestones).
        sort_by (None | str | Unset): One of: position, target_date, title, closed_at, created_at,
            project_name. `project_name` orders the projects; any other key orders each project's
            milestones. Default: the org's project order, then each project's milestone order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        filterproject (list[str] | None | Unset): Project ids, comma-separated or repeated.
        filterstatus (list[str] | None | Unset): `open` or `closed`.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | OrgMilestonesOut | Problem]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        sort_by=sort_by,
        sort_order=sort_order,
        filterproject=filterproject,
        filterstatus=filterstatus,
        if_none_match=if_none_match,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    org_id: str,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    filterproject: list[str] | None | Unset = UNSET,
    filterstatus: list[str] | None | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Any | OrgMilestonesOut | Problem | None:
    """Every milestone you can read in an organization, grouped by project

     Every live milestone in the projects you can read, grouped by project - the shape of `GET
    /v1/goals`. Each milestone carries its task roll-up and `project_name`; each group
    `milestones_tasks_total` / `milestones_tasks_completed`. Not paginated.

    - **Who sees what:** the projects you can read (a guest: only the projects they are a member of).
    403 when you are not a member of the organization.
    - **Order:** the organization's project order, then each project's milestones by position.
    - **Filters:** `filter[project]` (project ids) and `filter[status]` (`open` / `closed`); the sums
    count what is returned.
    - **Sort:** `sort_by=project_name` orders the projects; any other key orders each project's
    milestones.

    Args:
        org_id (str): Organization scope; the caller must be a member (a guest sees only its
            projects' milestones).
        sort_by (None | str | Unset): One of: position, target_date, title, closed_at, created_at,
            project_name. `project_name` orders the projects; any other key orders each project's
            milestones. Default: the org's project order, then each project's milestone order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        filterproject (list[str] | None | Unset): Project ids, comma-separated or repeated.
        filterstatus (list[str] | None | Unset): `open` or `closed`.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | OrgMilestonesOut | Problem
    """

    return sync_detailed(
        client=client,
        org_id=org_id,
        sort_by=sort_by,
        sort_order=sort_order,
        filterproject=filterproject,
        filterstatus=filterstatus,
        if_none_match=if_none_match,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    org_id: str,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    filterproject: list[str] | None | Unset = UNSET,
    filterstatus: list[str] | None | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Response[Any | OrgMilestonesOut | Problem]:
    """Every milestone you can read in an organization, grouped by project

     Every live milestone in the projects you can read, grouped by project - the shape of `GET
    /v1/goals`. Each milestone carries its task roll-up and `project_name`; each group
    `milestones_tasks_total` / `milestones_tasks_completed`. Not paginated.

    - **Who sees what:** the projects you can read (a guest: only the projects they are a member of).
    403 when you are not a member of the organization.
    - **Order:** the organization's project order, then each project's milestones by position.
    - **Filters:** `filter[project]` (project ids) and `filter[status]` (`open` / `closed`); the sums
    count what is returned.
    - **Sort:** `sort_by=project_name` orders the projects; any other key orders each project's
    milestones.

    Args:
        org_id (str): Organization scope; the caller must be a member (a guest sees only its
            projects' milestones).
        sort_by (None | str | Unset): One of: position, target_date, title, closed_at, created_at,
            project_name. `project_name` orders the projects; any other key orders each project's
            milestones. Default: the org's project order, then each project's milestone order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        filterproject (list[str] | None | Unset): Project ids, comma-separated or repeated.
        filterstatus (list[str] | None | Unset): `open` or `closed`.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | OrgMilestonesOut | Problem]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        sort_by=sort_by,
        sort_order=sort_order,
        filterproject=filterproject,
        filterstatus=filterstatus,
        if_none_match=if_none_match,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    org_id: str,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    filterproject: list[str] | None | Unset = UNSET,
    filterstatus: list[str] | None | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Any | OrgMilestonesOut | Problem | None:
    """Every milestone you can read in an organization, grouped by project

     Every live milestone in the projects you can read, grouped by project - the shape of `GET
    /v1/goals`. Each milestone carries its task roll-up and `project_name`; each group
    `milestones_tasks_total` / `milestones_tasks_completed`. Not paginated.

    - **Who sees what:** the projects you can read (a guest: only the projects they are a member of).
    403 when you are not a member of the organization.
    - **Order:** the organization's project order, then each project's milestones by position.
    - **Filters:** `filter[project]` (project ids) and `filter[status]` (`open` / `closed`); the sums
    count what is returned.
    - **Sort:** `sort_by=project_name` orders the projects; any other key orders each project's
    milestones.

    Args:
        org_id (str): Organization scope; the caller must be a member (a guest sees only its
            projects' milestones).
        sort_by (None | str | Unset): One of: position, target_date, title, closed_at, created_at,
            project_name. `project_name` orders the projects; any other key orders each project's
            milestones. Default: the org's project order, then each project's milestone order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        filterproject (list[str] | None | Unset): Project ids, comma-separated or repeated.
        filterstatus (list[str] | None | Unset): `open` or `closed`.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | OrgMilestonesOut | Problem
    """

    return (
        await asyncio_detailed(
            client=client,
            org_id=org_id,
            sort_by=sort_by,
            sort_order=sort_order,
            filterproject=filterproject,
            filterstatus=filterstatus,
            if_none_match=if_none_match,
        )
    ).parsed
