# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.milestone_task_unfiled import MilestoneTaskUnfiled
from ...models.problem import Problem
from typing import cast


def _get_kwargs(
    project_id: str,
    milestone_id: str,
    task_id: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/v1/projects/{project_id}/milestones/{milestone_id}/tasks/{task_id}".format(
            project_id=quote(str(project_id), safe=""),
            milestone_id=quote(str(milestone_id), safe=""),
            task_id=quote(str(task_id), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> MilestoneTaskUnfiled | Problem | None:
    if response.status_code == 200:
        response_200 = MilestoneTaskUnfiled.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[MilestoneTaskUnfiled | Problem]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    project_id: str,
    milestone_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
) -> Response[MilestoneTaskUnfiled | Problem]:
    """Take a task out of a milestone

     Take the task out of the milestone (`milestone_id` → null); it keeps its project and is never
    deleted.

    Args:
        project_id (str):
        milestone_id (str):
        task_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[MilestoneTaskUnfiled | Problem]
    """

    kwargs = _get_kwargs(
        project_id=project_id,
        milestone_id=milestone_id,
        task_id=task_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    project_id: str,
    milestone_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
) -> MilestoneTaskUnfiled | Problem | None:
    """Take a task out of a milestone

     Take the task out of the milestone (`milestone_id` → null); it keeps its project and is never
    deleted.

    Args:
        project_id (str):
        milestone_id (str):
        task_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        MilestoneTaskUnfiled | Problem
    """

    return sync_detailed(
        project_id=project_id,
        milestone_id=milestone_id,
        task_id=task_id,
        client=client,
    ).parsed


async def asyncio_detailed(
    project_id: str,
    milestone_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
) -> Response[MilestoneTaskUnfiled | Problem]:
    """Take a task out of a milestone

     Take the task out of the milestone (`milestone_id` → null); it keeps its project and is never
    deleted.

    Args:
        project_id (str):
        milestone_id (str):
        task_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[MilestoneTaskUnfiled | Problem]
    """

    kwargs = _get_kwargs(
        project_id=project_id,
        milestone_id=milestone_id,
        task_id=task_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    project_id: str,
    milestone_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
) -> MilestoneTaskUnfiled | Problem | None:
    """Take a task out of a milestone

     Take the task out of the milestone (`milestone_id` → null); it keeps its project and is never
    deleted.

    Args:
        project_id (str):
        milestone_id (str):
        task_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        MilestoneTaskUnfiled | Problem
    """

    return (
        await asyncio_detailed(
            project_id=project_id,
            milestone_id=milestone_id,
            task_id=task_id,
            client=client,
        )
    ).parsed
