# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.acknowledgement import Acknowledgement
from ...models.problem import Problem
from typing import cast


def _get_kwargs(
    section_id: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/v1/sections/{section_id}".format(
            section_id=quote(str(section_id), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Acknowledgement | Problem | None:
    if response.status_code == 200:
        response_200 = Acknowledgement.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Acknowledgement | Problem]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    section_id: str,
    *,
    client: AuthenticatedClient,
) -> Response[Acknowledgement | Problem]:
    """Delete a section

     Delete a section. **Tasks are never deleted**: the tasks that were in it become unsectioned in this
    scope.

    Args:
        section_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Acknowledgement | Problem]
    """

    kwargs = _get_kwargs(
        section_id=section_id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    section_id: str,
    *,
    client: AuthenticatedClient,
) -> Acknowledgement | Problem | None:
    """Delete a section

     Delete a section. **Tasks are never deleted**: the tasks that were in it become unsectioned in this
    scope.

    Args:
        section_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Acknowledgement | Problem
    """

    return sync_detailed(
        section_id=section_id,
        client=client,
    ).parsed


async def asyncio_detailed(
    section_id: str,
    *,
    client: AuthenticatedClient,
) -> Response[Acknowledgement | Problem]:
    """Delete a section

     Delete a section. **Tasks are never deleted**: the tasks that were in it become unsectioned in this
    scope.

    Args:
        section_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Acknowledgement | Problem]
    """

    kwargs = _get_kwargs(
        section_id=section_id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    section_id: str,
    *,
    client: AuthenticatedClient,
) -> Acknowledgement | Problem | None:
    """Delete a section

     Delete a section. **Tasks are never deleted**: the tasks that were in it become unsectioned in this
    scope.

    Args:
        section_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Acknowledgement | Problem
    """

    return (
        await asyncio_detailed(
            section_id=section_id,
            client=client,
        )
    ).parsed
