# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.problem import Problem
from ...models.project_goals_out import ProjectGoalsOut
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    project_id: str,
    *,
    include_tasks: bool | Unset = False,
    limit: int | Unset = 1000,
    cursor: None | str | Unset = UNSET,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    if_none_match: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(if_none_match, Unset):
        headers["If-None-Match"] = if_none_match

    params: dict[str, Any] = {}

    params["include_tasks"] = include_tasks

    params["limit"] = limit

    json_cursor: None | str | Unset
    if isinstance(cursor, Unset):
        json_cursor = UNSET
    else:
        json_cursor = cursor
    params["cursor"] = json_cursor

    json_sort_by: None | str | Unset
    if isinstance(sort_by, Unset):
        json_sort_by = UNSET
    else:
        json_sort_by = sort_by
    params["sort_by"] = json_sort_by

    params["sort_order"] = sort_order

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/v1/projects/{project_id}/goals".format(
            project_id=quote(str(project_id), safe=""),
        ),
        "params": params,
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | Problem | ProjectGoalsOut | None:
    if response.status_code == 200:
        response_200 = ProjectGoalsOut.from_dict(response.json())

        return response_200

    if response.status_code == 304:
        response_304 = cast(Any, None)
        return response_304

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | Problem | ProjectGoalsOut]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    project_id: str,
    *,
    client: AuthenticatedClient,
    include_tasks: bool | Unset = False,
    limit: int | Unset = 1000,
    cursor: None | str | Unset = UNSET,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    if_none_match: str | Unset = UNSET,
) -> Response[Any | Problem | ProjectGoalsOut]:
    """List a project's goals

     The project's goals by position, paginated as `{data, next_cursor}`; the project-level sums are
    returned beside `data`.

    Args:
        project_id (str):
        include_tasks (bool | Unset): Embed each goal's task rows (the caller's readable ones).
            Default: False.
        limit (int | Unset): Page size; default 1000, capped at 1000. Default: 1000.
        cursor (None | str | Unset): The previous page's `next_cursor`, echoed back verbatim
        sort_by (None | str | Unset): One of: position, name, target_date, created_at. Default:
            the list's natural order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Problem | ProjectGoalsOut]
    """

    kwargs = _get_kwargs(
        project_id=project_id,
        include_tasks=include_tasks,
        limit=limit,
        cursor=cursor,
        sort_by=sort_by,
        sort_order=sort_order,
        if_none_match=if_none_match,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    project_id: str,
    *,
    client: AuthenticatedClient,
    include_tasks: bool | Unset = False,
    limit: int | Unset = 1000,
    cursor: None | str | Unset = UNSET,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    if_none_match: str | Unset = UNSET,
) -> Any | Problem | ProjectGoalsOut | None:
    """List a project's goals

     The project's goals by position, paginated as `{data, next_cursor}`; the project-level sums are
    returned beside `data`.

    Args:
        project_id (str):
        include_tasks (bool | Unset): Embed each goal's task rows (the caller's readable ones).
            Default: False.
        limit (int | Unset): Page size; default 1000, capped at 1000. Default: 1000.
        cursor (None | str | Unset): The previous page's `next_cursor`, echoed back verbatim
        sort_by (None | str | Unset): One of: position, name, target_date, created_at. Default:
            the list's natural order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Problem | ProjectGoalsOut
    """

    return sync_detailed(
        project_id=project_id,
        client=client,
        include_tasks=include_tasks,
        limit=limit,
        cursor=cursor,
        sort_by=sort_by,
        sort_order=sort_order,
        if_none_match=if_none_match,
    ).parsed


async def asyncio_detailed(
    project_id: str,
    *,
    client: AuthenticatedClient,
    include_tasks: bool | Unset = False,
    limit: int | Unset = 1000,
    cursor: None | str | Unset = UNSET,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    if_none_match: str | Unset = UNSET,
) -> Response[Any | Problem | ProjectGoalsOut]:
    """List a project's goals

     The project's goals by position, paginated as `{data, next_cursor}`; the project-level sums are
    returned beside `data`.

    Args:
        project_id (str):
        include_tasks (bool | Unset): Embed each goal's task rows (the caller's readable ones).
            Default: False.
        limit (int | Unset): Page size; default 1000, capped at 1000. Default: 1000.
        cursor (None | str | Unset): The previous page's `next_cursor`, echoed back verbatim
        sort_by (None | str | Unset): One of: position, name, target_date, created_at. Default:
            the list's natural order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Problem | ProjectGoalsOut]
    """

    kwargs = _get_kwargs(
        project_id=project_id,
        include_tasks=include_tasks,
        limit=limit,
        cursor=cursor,
        sort_by=sort_by,
        sort_order=sort_order,
        if_none_match=if_none_match,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    project_id: str,
    *,
    client: AuthenticatedClient,
    include_tasks: bool | Unset = False,
    limit: int | Unset = 1000,
    cursor: None | str | Unset = UNSET,
    sort_by: None | str | Unset = UNSET,
    sort_order: str | Unset = "asc",
    if_none_match: str | Unset = UNSET,
) -> Any | Problem | ProjectGoalsOut | None:
    """List a project's goals

     The project's goals by position, paginated as `{data, next_cursor}`; the project-level sums are
    returned beside `data`.

    Args:
        project_id (str):
        include_tasks (bool | Unset): Embed each goal's task rows (the caller's readable ones).
            Default: False.
        limit (int | Unset): Page size; default 1000, capped at 1000. Default: 1000.
        cursor (None | str | Unset): The previous page's `next_cursor`, echoed back verbatim
        sort_by (None | str | Unset): One of: position, name, target_date, created_at. Default:
            the list's natural order.
        sort_order (str | Unset): `asc` or `desc` Default: 'asc'.
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Problem | ProjectGoalsOut
    """

    return (
        await asyncio_detailed(
            project_id=project_id,
            client=client,
            include_tasks=include_tasks,
            limit=limit,
            cursor=cursor,
            sort_by=sort_by,
            sort_order=sort_order,
            if_none_match=if_none_match,
        )
    ).parsed
