# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.organization_in_db import OrganizationInDB
from ...models.problem import Problem
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    org_id: str,
    *,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(authorization, Unset):
        headers["authorization"] = authorization

    if not isinstance(if_none_match, Unset):
        headers["If-None-Match"] = if_none_match

    params: dict[str, Any] = {}

    params["is_registration"] = is_registration

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/v1/organizations/{org_id}".format(
            org_id=quote(str(org_id), safe=""),
        ),
        "params": params,
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | OrganizationInDB | Problem | None:
    if response.status_code == 200:
        response_200 = OrganizationInDB.from_dict(response.json())

        return response_200

    if response.status_code == 304:
        response_304 = cast(Any, None)
        return response_304

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | OrganizationInDB | Problem]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    org_id: str,
    *,
    client: AuthenticatedClient,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Response[Any | OrganizationInDB | Problem]:
    """Read an organization

    Args:
        org_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | OrganizationInDB | Problem]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        is_registration=is_registration,
        authorization=authorization,
        if_none_match=if_none_match,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    org_id: str,
    *,
    client: AuthenticatedClient,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Any | OrganizationInDB | Problem | None:
    """Read an organization

    Args:
        org_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | OrganizationInDB | Problem
    """

    return sync_detailed(
        org_id=org_id,
        client=client,
        is_registration=is_registration,
        authorization=authorization,
        if_none_match=if_none_match,
    ).parsed


async def asyncio_detailed(
    org_id: str,
    *,
    client: AuthenticatedClient,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Response[Any | OrganizationInDB | Problem]:
    """Read an organization

    Args:
        org_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | OrganizationInDB | Problem]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        is_registration=is_registration,
        authorization=authorization,
        if_none_match=if_none_match,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    org_id: str,
    *,
    client: AuthenticatedClient,
    is_registration: bool | Unset = False,
    authorization: str | Unset = UNSET,
    if_none_match: str | Unset = UNSET,
) -> Any | OrganizationInDB | Problem | None:
    """Read an organization

    Args:
        org_id (str):
        is_registration (bool | Unset):  Default: False.
        authorization (str | Unset):
        if_none_match (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | OrganizationInDB | Problem
    """

    return (
        await asyncio_detailed(
            org_id=org_id,
            client=client,
            is_registration=is_registration,
            authorization=authorization,
            if_none_match=if_none_match,
        )
    ).parsed
