# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.problem import Problem
from ...models.project_resource_in_db import ProjectResourceInDB
from ...models.task_attachment_in_db import TaskAttachmentInDB
from ...models.upload_complete_in import UploadCompleteIn
from ...types import UNSET, Unset
from typing import cast


def _get_kwargs(
    upload_id: str,
    *,
    body: None | Unset | UploadCompleteIn = UNSET,
    idempotency_key: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(idempotency_key, Unset):
        headers["Idempotency-Key"] = idempotency_key

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/v1/uploads/{upload_id}/complete".format(
            upload_id=quote(str(upload_id), safe=""),
        ),
    }

    if isinstance(body, UploadCompleteIn):
        _kwargs["json"] = body.to_dict()
    else:
        _kwargs["json"] = body

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Problem | ProjectResourceInDB | TaskAttachmentInDB | None:
    if response.status_code == 200:

        def _parse_response_200(data: object) -> ProjectResourceInDB | TaskAttachmentInDB:
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                response_200_type_0 = TaskAttachmentInDB.from_dict(data)

                return response_200_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            if not isinstance(data, dict):
                raise TypeError()
            response_200_type_1 = ProjectResourceInDB.from_dict(data)

            return response_200_type_1

        response_200 = _parse_response_200(response.json())

        return response_200

    if response.status_code == 201:

        def _parse_response_201(data: object) -> ProjectResourceInDB | TaskAttachmentInDB:
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                response_201_type_0 = TaskAttachmentInDB.from_dict(data)

                return response_201_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            if not isinstance(data, dict):
                raise TypeError()
            response_201_type_1 = ProjectResourceInDB.from_dict(data)

            return response_201_type_1

        response_201 = _parse_response_201(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Problem.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Problem.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = Problem.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = Problem.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Problem.from_dict(response.json())

        return response_409

    if response.status_code == 412:
        response_412 = Problem.from_dict(response.json())

        return response_412

    if response.status_code == 422:
        response_422 = Problem.from_dict(response.json())

        return response_422

    if response.status_code == 429:
        response_429 = Problem.from_dict(response.json())

        return response_429

    if response.status_code == 500:
        response_500 = Problem.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Problem | ProjectResourceInDB | TaskAttachmentInDB]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    upload_id: str,
    *,
    client: AuthenticatedClient,
    body: None | Unset | UploadCompleteIn = UNSET,
    idempotency_key: str | Unset = UNSET,
) -> Response[Problem | ProjectResourceInDB | TaskAttachmentInDB]:
    """Finish a direct upload: the file is checked and becomes an attachment or a project file

     Finalize: check the file that was actually uploaded, then create the row exactly as the multipart
    route does.

    Answers the SAME object the multipart route answers. 201 the first time; a repeat answers 200 with
    the same row
    rather than storing the file twice.

    Args:
        upload_id (str):
        idempotency_key (str | Unset):
        body (None | Unset | UploadCompleteIn):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Problem | ProjectResourceInDB | TaskAttachmentInDB]
    """

    kwargs = _get_kwargs(
        upload_id=upload_id,
        body=body,
        idempotency_key=idempotency_key,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    upload_id: str,
    *,
    client: AuthenticatedClient,
    body: None | Unset | UploadCompleteIn = UNSET,
    idempotency_key: str | Unset = UNSET,
) -> Problem | ProjectResourceInDB | TaskAttachmentInDB | None:
    """Finish a direct upload: the file is checked and becomes an attachment or a project file

     Finalize: check the file that was actually uploaded, then create the row exactly as the multipart
    route does.

    Answers the SAME object the multipart route answers. 201 the first time; a repeat answers 200 with
    the same row
    rather than storing the file twice.

    Args:
        upload_id (str):
        idempotency_key (str | Unset):
        body (None | Unset | UploadCompleteIn):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Problem | ProjectResourceInDB | TaskAttachmentInDB
    """

    return sync_detailed(
        upload_id=upload_id,
        client=client,
        body=body,
        idempotency_key=idempotency_key,
    ).parsed


async def asyncio_detailed(
    upload_id: str,
    *,
    client: AuthenticatedClient,
    body: None | Unset | UploadCompleteIn = UNSET,
    idempotency_key: str | Unset = UNSET,
) -> Response[Problem | ProjectResourceInDB | TaskAttachmentInDB]:
    """Finish a direct upload: the file is checked and becomes an attachment or a project file

     Finalize: check the file that was actually uploaded, then create the row exactly as the multipart
    route does.

    Answers the SAME object the multipart route answers. 201 the first time; a repeat answers 200 with
    the same row
    rather than storing the file twice.

    Args:
        upload_id (str):
        idempotency_key (str | Unset):
        body (None | Unset | UploadCompleteIn):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Problem | ProjectResourceInDB | TaskAttachmentInDB]
    """

    kwargs = _get_kwargs(
        upload_id=upload_id,
        body=body,
        idempotency_key=idempotency_key,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    upload_id: str,
    *,
    client: AuthenticatedClient,
    body: None | Unset | UploadCompleteIn = UNSET,
    idempotency_key: str | Unset = UNSET,
) -> Problem | ProjectResourceInDB | TaskAttachmentInDB | None:
    """Finish a direct upload: the file is checked and becomes an attachment or a project file

     Finalize: check the file that was actually uploaded, then create the row exactly as the multipart
    route does.

    Answers the SAME object the multipart route answers. 201 the first time; a repeat answers 200 with
    the same row
    rather than storing the file twice.

    Args:
        upload_id (str):
        idempotency_key (str | Unset):
        body (None | Unset | UploadCompleteIn):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Problem | ProjectResourceInDB | TaskAttachmentInDB
    """

    return (
        await asyncio_detailed(
            upload_id=upload_id,
            client=client,
            body=body,
            idempotency_key=idempotency_key,
        )
    ).parsed
