# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
import datetime

if TYPE_CHECKING:
    from ..models.audit_export_row_after_type_0 import AuditExportRowAfterType0
    from ..models.audit_export_row_before_type_0 import AuditExportRowBeforeType0


T = TypeVar("T", bound="AuditExportRow")


@_attrs_define
class AuditExportRow:
    """Returned by `audit.export_json`.

    Example:
        {'event_id': 1, 'created_at': '2026-09-25T12:00:00Z', 'org_id': 'O0001', 'action': 'org.updated',
            'resource_type': 'organization'}

    Attributes:
        event_id (int | Unset):
        created_at (datetime.datetime | Unset):
        org_id (str | Unset):
        action (str | Unset):
        resource_type (str | Unset):
        resource_id (None | str | Unset):
        project_id (None | str | Unset):
        actor_kind (str | Unset):
        actor_user_id (None | str | Unset):
        actor_username (None | str | Unset):
        actor_display (None | str | Unset):
        before (AuditExportRowBeforeType0 | None | Unset):
        after (AuditExportRowAfterType0 | None | Unset):
        ip (None | str | Unset):
        user_agent (None | str | Unset):
        request_id (None | str | Unset):
    """

    event_id: int | Unset = UNSET
    created_at: datetime.datetime | Unset = UNSET
    org_id: str | Unset = UNSET
    action: str | Unset = UNSET
    resource_type: str | Unset = UNSET
    resource_id: None | str | Unset = UNSET
    project_id: None | str | Unset = UNSET
    actor_kind: str | Unset = UNSET
    actor_user_id: None | str | Unset = UNSET
    actor_username: None | str | Unset = UNSET
    actor_display: None | str | Unset = UNSET
    before: AuditExportRowBeforeType0 | None | Unset = UNSET
    after: AuditExportRowAfterType0 | None | Unset = UNSET
    ip: None | str | Unset = UNSET
    user_agent: None | str | Unset = UNSET
    request_id: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.audit_export_row_after_type_0 import AuditExportRowAfterType0  # noqa: PLC0415
        from ..models.audit_export_row_before_type_0 import AuditExportRowBeforeType0  # noqa: PLC0415

        event_id = self.event_id

        created_at: str | Unset = UNSET
        if not isinstance(self.created_at, Unset):
            created_at = self.created_at.isoformat()

        org_id = self.org_id

        action = self.action

        resource_type = self.resource_type

        resource_id: None | str | Unset
        if isinstance(self.resource_id, Unset):
            resource_id = UNSET
        else:
            resource_id = self.resource_id

        project_id: None | str | Unset
        if isinstance(self.project_id, Unset):
            project_id = UNSET
        else:
            project_id = self.project_id

        actor_kind = self.actor_kind

        actor_user_id: None | str | Unset
        if isinstance(self.actor_user_id, Unset):
            actor_user_id = UNSET
        else:
            actor_user_id = self.actor_user_id

        actor_username: None | str | Unset
        if isinstance(self.actor_username, Unset):
            actor_username = UNSET
        else:
            actor_username = self.actor_username

        actor_display: None | str | Unset
        if isinstance(self.actor_display, Unset):
            actor_display = UNSET
        else:
            actor_display = self.actor_display

        before: dict[str, Any] | None | Unset
        if isinstance(self.before, Unset):
            before = UNSET
        elif isinstance(self.before, AuditExportRowBeforeType0):
            before = self.before.to_dict()
        else:
            before = self.before

        after: dict[str, Any] | None | Unset
        if isinstance(self.after, Unset):
            after = UNSET
        elif isinstance(self.after, AuditExportRowAfterType0):
            after = self.after.to_dict()
        else:
            after = self.after

        ip: None | str | Unset
        if isinstance(self.ip, Unset):
            ip = UNSET
        else:
            ip = self.ip

        user_agent: None | str | Unset
        if isinstance(self.user_agent, Unset):
            user_agent = UNSET
        else:
            user_agent = self.user_agent

        request_id: None | str | Unset
        if isinstance(self.request_id, Unset):
            request_id = UNSET
        else:
            request_id = self.request_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if event_id is not UNSET:
            field_dict["event_id"] = event_id
        if created_at is not UNSET:
            field_dict["created_at"] = created_at
        if org_id is not UNSET:
            field_dict["org_id"] = org_id
        if action is not UNSET:
            field_dict["action"] = action
        if resource_type is not UNSET:
            field_dict["resource_type"] = resource_type
        if resource_id is not UNSET:
            field_dict["resource_id"] = resource_id
        if project_id is not UNSET:
            field_dict["project_id"] = project_id
        if actor_kind is not UNSET:
            field_dict["actor_kind"] = actor_kind
        if actor_user_id is not UNSET:
            field_dict["actor_user_id"] = actor_user_id
        if actor_username is not UNSET:
            field_dict["actor_username"] = actor_username
        if actor_display is not UNSET:
            field_dict["actor_display"] = actor_display
        if before is not UNSET:
            field_dict["before"] = before
        if after is not UNSET:
            field_dict["after"] = after
        if ip is not UNSET:
            field_dict["ip"] = ip
        if user_agent is not UNSET:
            field_dict["user_agent"] = user_agent
        if request_id is not UNSET:
            field_dict["request_id"] = request_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.audit_export_row_after_type_0 import AuditExportRowAfterType0  # noqa: PLC0415
        from ..models.audit_export_row_before_type_0 import AuditExportRowBeforeType0  # noqa: PLC0415

        d = dict(src_dict)
        event_id = d.pop("event_id", UNSET)

        _created_at = d.pop("created_at", UNSET)
        created_at: datetime.datetime | Unset
        if isinstance(_created_at, Unset):
            created_at = UNSET
        else:
            created_at = datetime.datetime.fromisoformat(_created_at)

        org_id = d.pop("org_id", UNSET)

        action = d.pop("action", UNSET)

        resource_type = d.pop("resource_type", UNSET)

        def _parse_resource_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        resource_id = _parse_resource_id(d.pop("resource_id", UNSET))

        def _parse_project_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        project_id = _parse_project_id(d.pop("project_id", UNSET))

        actor_kind = d.pop("actor_kind", UNSET)

        def _parse_actor_user_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        actor_user_id = _parse_actor_user_id(d.pop("actor_user_id", UNSET))

        def _parse_actor_username(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        actor_username = _parse_actor_username(d.pop("actor_username", UNSET))

        def _parse_actor_display(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        actor_display = _parse_actor_display(d.pop("actor_display", UNSET))

        def _parse_before(data: object) -> AuditExportRowBeforeType0 | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                before_type_0 = AuditExportRowBeforeType0.from_dict(data)

                return before_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(AuditExportRowBeforeType0 | None | Unset, data)

        before = _parse_before(d.pop("before", UNSET))

        def _parse_after(data: object) -> AuditExportRowAfterType0 | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                after_type_0 = AuditExportRowAfterType0.from_dict(data)

                return after_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(AuditExportRowAfterType0 | None | Unset, data)

        after = _parse_after(d.pop("after", UNSET))

        def _parse_ip(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        ip = _parse_ip(d.pop("ip", UNSET))

        def _parse_user_agent(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        user_agent = _parse_user_agent(d.pop("user_agent", UNSET))

        def _parse_request_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        request_id = _parse_request_id(d.pop("request_id", UNSET))

        audit_export_row = cls(
            event_id=event_id,
            created_at=created_at,
            org_id=org_id,
            action=action,
            resource_type=resource_type,
            resource_id=resource_id,
            project_id=project_id,
            actor_kind=actor_kind,
            actor_user_id=actor_user_id,
            actor_username=actor_username,
            actor_display=actor_display,
            before=before,
            after=after,
            ip=ip,
            user_agent=user_agent,
            request_id=request_id,
        )

        audit_export_row.additional_properties = d
        return audit_export_row

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
