# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

Environment = Literal["development", "production", "uat"]

ENVIRONMENT_VALUES: set[Environment] = {
    "development",
    "production",
    "uat",
}


def check_environment(value: str) -> Environment:
    if value in ENVIRONMENT_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {ENVIRONMENT_VALUES!r}")
