# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

McpArtefactLang = Literal["bash", "json", "text"]

MCP_ARTEFACT_LANG_VALUES: set[McpArtefactLang] = {
    "bash",
    "json",
    "text",
}


def check_mcp_artefact_lang(value: str) -> McpArtefactLang:
    if value in MCP_ARTEFACT_LANG_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {MCP_ARTEFACT_LANG_VALUES!r}")
