# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.mcp_package_registry import check_mcp_package_registry
from ..models.mcp_package_registry import McpPackageRegistry
from typing import cast


T = TypeVar("T", bound="McpPackage")


@_attrs_define
class McpPackage:
    """Part of `McpStdio`.

    Attributes:
        package (str):
        registry (McpPackageRegistry):
        command (str):
        args (list[str]):
    """

    package: str
    registry: McpPackageRegistry
    command: str
    args: list[str]
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        package = self.package

        registry: str = self.registry

        command = self.command

        args = self.args

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "package": package,
                "registry": registry,
                "command": command,
                "args": args,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        package = d.pop("package")

        registry = check_mcp_package_registry(d.pop("registry"))

        command = d.pop("command")

        args = cast(list[str], d.pop("args"))

        mcp_package = cls(
            package=package,
            registry=registry,
            command=command,
            args=args,
        )

        mcp_package.additional_properties = d
        return mcp_package

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
