# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast

if TYPE_CHECKING:
    from ..models.mcp_stdio_env import McpStdioEnv
    from ..models.mcp_stdio_flags import McpStdioFlags
    from ..models.mcp_stdio_packages import McpStdioPackages


T = TypeVar("T", bound="McpStdio")


@_attrs_define
class McpStdio:
    """Part of `McpClientsOut`.

    Attributes:
        packages (McpStdioPackages): `npx` and `uvx`
        default_api_url (str): The API the packages call when `TASKADENCE_API_URL` is unset
        env (McpStdioEnv): The packages' environment variables: token, api_url, readonly, groups
        flags (McpStdioFlags): The same as command-line flags (flags win)
    """

    packages: McpStdioPackages
    default_api_url: str
    env: McpStdioEnv
    flags: McpStdioFlags
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.mcp_stdio_env import McpStdioEnv  # noqa: PLC0415
        from ..models.mcp_stdio_flags import McpStdioFlags  # noqa: PLC0415
        from ..models.mcp_stdio_packages import McpStdioPackages  # noqa: PLC0415

        packages = self.packages.to_dict()

        default_api_url = self.default_api_url

        env = self.env.to_dict()

        flags = self.flags.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "packages": packages,
                "default_api_url": default_api_url,
                "env": env,
                "flags": flags,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.mcp_stdio_env import McpStdioEnv  # noqa: PLC0415
        from ..models.mcp_stdio_flags import McpStdioFlags  # noqa: PLC0415
        from ..models.mcp_stdio_packages import McpStdioPackages  # noqa: PLC0415

        d = dict(src_dict)
        packages = McpStdioPackages.from_dict(d.pop("packages"))

        default_api_url = d.pop("default_api_url")

        env = McpStdioEnv.from_dict(d.pop("env"))

        flags = McpStdioFlags.from_dict(d.pop("flags"))

        mcp_stdio = cls(
            packages=packages,
            default_api_url=default_api_url,
            env=env,
            flags=flags,
        )

        mcp_stdio.additional_properties = d
        return mcp_stdio

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
