# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

MfaRequirementEnum = Literal["admins", "all", "off"]

MFA_REQUIREMENT_ENUM_VALUES: set[MfaRequirementEnum] = {
    "admins",
    "all",
    "off",
}


def check_mfa_requirement_enum(value: str) -> MfaRequirementEnum:
    if value in MFA_REQUIREMENT_ENUM_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {MFA_REQUIREMENT_ENUM_VALUES!r}")
