# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast


T = TypeVar("T", bound="MilestoneTasksFile")


@_attrs_define
class MilestoneTasksFile:
    """`POST …/milestones/{milestone_id}/tasks` - file existing tasks of THIS project under the milestone (all-or-nothing).

    Attributes:
        task_ids (list[str]):
    """

    task_ids: list[str]
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        task_ids = self.task_ids

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "task_ids": task_ids,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        task_ids = cast(list[str], d.pop("task_ids"))

        milestone_tasks_file = cls(
            task_ids=task_ids,
        )

        return milestone_tasks_file
