# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

OAuthClientCreatedRegistration = Literal["developer", "dynamic"]

O_AUTH_CLIENT_CREATED_REGISTRATION_VALUES: set[OAuthClientCreatedRegistration] = {
    "developer",
    "dynamic",
}


def check_o_auth_client_created_registration(value: str) -> OAuthClientCreatedRegistration:
    if value in O_AUTH_CLIENT_CREATED_REGISTRATION_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {O_AUTH_CLIENT_CREATED_REGISTRATION_VALUES!r}")
