# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

ProblemType = Literal[
    "about:blank",
    "urn:taskadence:problem:idempotency-key-in-flight",
    "urn:taskadence:problem:idempotency-key-invalid",
    "urn:taskadence:problem:idempotency-key-reused",
    "urn:taskadence:problem:insufficient-scope",
    "urn:taskadence:problem:internal",
    "urn:taskadence:problem:invalid-parameter",
    "urn:taskadence:problem:precondition-failed",
    "urn:taskadence:problem:rate-limit",
    "urn:taskadence:problem:test-token-read-only",
    "urn:taskadence:problem:token-expired",
    "urn:taskadence:problem:token-invalid",
    "urn:taskadence:problem:token-policy",
    "urn:taskadence:problem:token-revoked",
    "urn:taskadence:problem:url-refused",
    "urn:taskadence:problem:validation",
]

PROBLEM_TYPE_VALUES: set[ProblemType] = {
    "about:blank",
    "urn:taskadence:problem:idempotency-key-in-flight",
    "urn:taskadence:problem:idempotency-key-invalid",
    "urn:taskadence:problem:idempotency-key-reused",
    "urn:taskadence:problem:insufficient-scope",
    "urn:taskadence:problem:internal",
    "urn:taskadence:problem:invalid-parameter",
    "urn:taskadence:problem:precondition-failed",
    "urn:taskadence:problem:rate-limit",
    "urn:taskadence:problem:test-token-read-only",
    "urn:taskadence:problem:token-expired",
    "urn:taskadence:problem:token-invalid",
    "urn:taskadence:problem:token-policy",
    "urn:taskadence:problem:token-revoked",
    "urn:taskadence:problem:url-refused",
    "urn:taskadence:problem:validation",
}


def check_problem_type(value: str) -> ProblemType:
    if value in PROBLEM_TYPE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {PROBLEM_TYPE_VALUES!r}")
