# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast


T = TypeVar("T", bound="ProjectResourceUpdate")


@_attrs_define
class ProjectResourceUpdate:
    """The request body of `project-resources.update`.

    Attributes:
        resource_name (None | str | Unset):
        resource_url (None | str | Unset):
        resource_type (None | str | Unset):
        is_active (bool | None | Unset):
    """

    resource_name: None | str | Unset = UNSET
    resource_url: None | str | Unset = UNSET
    resource_type: None | str | Unset = UNSET
    is_active: bool | None | Unset = UNSET
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        resource_name: None | str | Unset
        if isinstance(self.resource_name, Unset):
            resource_name = UNSET
        else:
            resource_name = self.resource_name

        resource_url: None | str | Unset
        if isinstance(self.resource_url, Unset):
            resource_url = UNSET
        else:
            resource_url = self.resource_url

        resource_type: None | str | Unset
        if isinstance(self.resource_type, Unset):
            resource_type = UNSET
        else:
            resource_type = self.resource_type

        is_active: bool | None | Unset
        if isinstance(self.is_active, Unset):
            is_active = UNSET
        else:
            is_active = self.is_active

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if resource_name is not UNSET:
            field_dict["resource_name"] = resource_name
        if resource_url is not UNSET:
            field_dict["resource_url"] = resource_url
        if resource_type is not UNSET:
            field_dict["resource_type"] = resource_type
        if is_active is not UNSET:
            field_dict["is_active"] = is_active

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)

        def _parse_resource_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        resource_name = _parse_resource_name(d.pop("resource_name", UNSET))

        def _parse_resource_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        resource_url = _parse_resource_url(d.pop("resource_url", UNSET))

        def _parse_resource_type(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        resource_type = _parse_resource_type(d.pop("resource_type", UNSET))

        def _parse_is_active(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        is_active = _parse_is_active(d.pop("is_active", UNSET))

        project_resource_update = cls(
            resource_name=resource_name,
            resource_url=resource_url,
            resource_type=resource_type,
            is_active=is_active,
        )

        return project_resource_update
