# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
import datetime


T = TypeVar("T", bound="ProjectResourceInDB")


@_attrs_define
class ProjectResourceInDB:
    """Returned by `project-resources.create`, `project-resources.read`, `project-resources.update` and `project-
    resources.upload`.

        Attributes:
            project_id (str): Project ID (text) Example: project-1234.
            project_name (str): Project name Example: Project 1.
            resource_name (str): Resource name Example: API Docs.
            resource_id (str): Resource ID Example: RE0001.
            created_at (datetime.datetime | None):
            updated_at (datetime.datetime | None):
            deleted_at (datetime.datetime | None):
            resource_url (None | str | Unset): Resource URL Example: https://example.com/api-docs.pdf.
            resource_type (None | str | Unset): Type of resource Example: pdf.
            storage_path (None | str | Unset): Original File Storage Path
            is_active (bool | None | Unset): Is the resource active? Default: True. Example: True.
            created_by (None | str | Unset): Who created the resource
            updated_by (None | str | Unset): Who last updated the resource
            delete_reason (None | str | Unset): Reason for deletion
            url_expires_at (datetime.datetime | None | Unset): When `resource_url` stops working (null for a link resource)
            content_type (None | str | Unset): A stored file's detected type
    """

    project_id: str
    project_name: str
    resource_name: str
    resource_id: str
    created_at: datetime.datetime | None
    updated_at: datetime.datetime | None
    deleted_at: datetime.datetime | None
    resource_url: None | str | Unset = UNSET
    resource_type: None | str | Unset = UNSET
    storage_path: None | str | Unset = UNSET
    is_active: bool | None | Unset = True
    created_by: None | str | Unset = UNSET
    updated_by: None | str | Unset = UNSET
    delete_reason: None | str | Unset = UNSET
    url_expires_at: datetime.datetime | None | Unset = UNSET
    content_type: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        project_id = self.project_id

        project_name = self.project_name

        resource_name = self.resource_name

        resource_id = self.resource_id

        created_at: None | str
        if isinstance(self.created_at, datetime.datetime):
            created_at = self.created_at.isoformat()
        else:
            created_at = self.created_at

        updated_at: None | str
        if isinstance(self.updated_at, datetime.datetime):
            updated_at = self.updated_at.isoformat()
        else:
            updated_at = self.updated_at

        deleted_at: None | str
        if isinstance(self.deleted_at, datetime.datetime):
            deleted_at = self.deleted_at.isoformat()
        else:
            deleted_at = self.deleted_at

        resource_url: None | str | Unset
        if isinstance(self.resource_url, Unset):
            resource_url = UNSET
        else:
            resource_url = self.resource_url

        resource_type: None | str | Unset
        if isinstance(self.resource_type, Unset):
            resource_type = UNSET
        else:
            resource_type = self.resource_type

        storage_path: None | str | Unset
        if isinstance(self.storage_path, Unset):
            storage_path = UNSET
        else:
            storage_path = self.storage_path

        is_active: bool | None | Unset
        if isinstance(self.is_active, Unset):
            is_active = UNSET
        else:
            is_active = self.is_active

        created_by: None | str | Unset
        if isinstance(self.created_by, Unset):
            created_by = UNSET
        else:
            created_by = self.created_by

        updated_by: None | str | Unset
        if isinstance(self.updated_by, Unset):
            updated_by = UNSET
        else:
            updated_by = self.updated_by

        delete_reason: None | str | Unset
        if isinstance(self.delete_reason, Unset):
            delete_reason = UNSET
        else:
            delete_reason = self.delete_reason

        url_expires_at: None | str | Unset
        if isinstance(self.url_expires_at, Unset):
            url_expires_at = UNSET
        elif isinstance(self.url_expires_at, datetime.datetime):
            url_expires_at = self.url_expires_at.isoformat()
        else:
            url_expires_at = self.url_expires_at

        content_type: None | str | Unset
        if isinstance(self.content_type, Unset):
            content_type = UNSET
        else:
            content_type = self.content_type

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "project_id": project_id,
                "project_name": project_name,
                "resource_name": resource_name,
                "resource_id": resource_id,
                "created_at": created_at,
                "updated_at": updated_at,
                "deleted_at": deleted_at,
            }
        )
        if resource_url is not UNSET:
            field_dict["resource_url"] = resource_url
        if resource_type is not UNSET:
            field_dict["resource_type"] = resource_type
        if storage_path is not UNSET:
            field_dict["storage_path"] = storage_path
        if is_active is not UNSET:
            field_dict["is_active"] = is_active
        if created_by is not UNSET:
            field_dict["created_by"] = created_by
        if updated_by is not UNSET:
            field_dict["updated_by"] = updated_by
        if delete_reason is not UNSET:
            field_dict["delete_reason"] = delete_reason
        if url_expires_at is not UNSET:
            field_dict["url_expires_at"] = url_expires_at
        if content_type is not UNSET:
            field_dict["content_type"] = content_type

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        project_id = d.pop("project_id")

        project_name = d.pop("project_name")

        resource_name = d.pop("resource_name")

        resource_id = d.pop("resource_id")

        def _parse_created_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                created_at_type_0 = datetime.datetime.fromisoformat(data)

                return created_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        created_at = _parse_created_at(d.pop("created_at"))

        def _parse_updated_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                updated_at_type_0 = datetime.datetime.fromisoformat(data)

                return updated_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        updated_at = _parse_updated_at(d.pop("updated_at"))

        def _parse_deleted_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                deleted_at_type_0 = datetime.datetime.fromisoformat(data)

                return deleted_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        deleted_at = _parse_deleted_at(d.pop("deleted_at"))

        def _parse_resource_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        resource_url = _parse_resource_url(d.pop("resource_url", UNSET))

        def _parse_resource_type(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        resource_type = _parse_resource_type(d.pop("resource_type", UNSET))

        def _parse_storage_path(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        storage_path = _parse_storage_path(d.pop("storage_path", UNSET))

        def _parse_is_active(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        is_active = _parse_is_active(d.pop("is_active", UNSET))

        def _parse_created_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        created_by = _parse_created_by(d.pop("created_by", UNSET))

        def _parse_updated_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        updated_by = _parse_updated_by(d.pop("updated_by", UNSET))

        def _parse_delete_reason(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        delete_reason = _parse_delete_reason(d.pop("delete_reason", UNSET))

        def _parse_url_expires_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                url_expires_at_type_0 = datetime.datetime.fromisoformat(data)

                return url_expires_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        url_expires_at = _parse_url_expires_at(d.pop("url_expires_at", UNSET))

        def _parse_content_type(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        content_type = _parse_content_type(d.pop("content_type", UNSET))

        project_resource_in_db = cls(
            project_id=project_id,
            project_name=project_name,
            resource_name=resource_name,
            resource_id=resource_id,
            created_at=created_at,
            updated_at=updated_at,
            deleted_at=deleted_at,
            resource_url=resource_url,
            resource_type=resource_type,
            storage_path=storage_path,
            is_active=is_active,
            created_by=created_by,
            updated_by=updated_by,
            delete_reason=delete_reason,
            url_expires_at=url_expires_at,
            content_type=content_type,
        )

        project_resource_in_db.additional_properties = d
        return project_resource_in_db

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
