# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.project_role_enum import check_project_role_enum
from ..models.project_role_enum import ProjectRoleEnum
from ..types import UNSET, Unset
from typing import cast


T = TypeVar("T", bound="ProjectMemberUpdate")


@_attrs_define
class ProjectMemberUpdate:
    """The body of a project-member update. Every field is optional and omitted fields are left unchanged; `user_id` and
    `project_id` come from the path and need not be repeated.

        Attributes:
            designation (None | str | Unset): Designation name Example: developer.
            designation_id (None | str | Unset): The designation's id (a global designation or the organization's own). Send
                this or `designation` (a name, label or alias); responses carry both. Example: DG0001.
            role (None | str | Unset): The older role field (`owner` / `admin` / `member`); derived from `project_role` when
                omitted. Prefer `project_role`. Example: owner.
            project_role (None | ProjectRoleEnum | Unset): The member's role on the project; derived from `role` when
                omitted. Example: editor.
            is_active (bool | None | Unset): Whether the member is active. Omit to leave it unchanged. Example: True.
    """

    designation: None | str | Unset = UNSET
    designation_id: None | str | Unset = UNSET
    role: None | str | Unset = UNSET
    project_role: None | ProjectRoleEnum | Unset = UNSET
    is_active: bool | None | Unset = UNSET
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        designation: None | str | Unset
        if isinstance(self.designation, Unset):
            designation = UNSET
        else:
            designation = self.designation

        designation_id: None | str | Unset
        if isinstance(self.designation_id, Unset):
            designation_id = UNSET
        else:
            designation_id = self.designation_id

        role: None | str | Unset
        if isinstance(self.role, Unset):
            role = UNSET
        else:
            role = self.role

        project_role: None | str | Unset
        if isinstance(self.project_role, Unset):
            project_role = UNSET
        elif isinstance(self.project_role, str):
            project_role = self.project_role
        else:
            project_role = self.project_role

        is_active: bool | None | Unset
        if isinstance(self.is_active, Unset):
            is_active = UNSET
        else:
            is_active = self.is_active

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if designation is not UNSET:
            field_dict["designation"] = designation
        if designation_id is not UNSET:
            field_dict["designation_id"] = designation_id
        if role is not UNSET:
            field_dict["role"] = role
        if project_role is not UNSET:
            field_dict["project_role"] = project_role
        if is_active is not UNSET:
            field_dict["is_active"] = is_active

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)

        def _parse_designation(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        designation = _parse_designation(d.pop("designation", UNSET))

        def _parse_designation_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        designation_id = _parse_designation_id(d.pop("designation_id", UNSET))

        def _parse_role(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        role = _parse_role(d.pop("role", UNSET))

        def _parse_project_role(data: object) -> None | ProjectRoleEnum | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                project_role_type_0 = check_project_role_enum(data)

                return project_role_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ProjectRoleEnum | Unset, data)

        project_role = _parse_project_role(d.pop("project_role", UNSET))

        def _parse_is_active(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        is_active = _parse_is_active(d.pop("is_active", UNSET))

        project_member_update = cls(
            designation=designation,
            designation_id=designation_id,
            role=role,
            project_role=project_role,
            is_active=is_active,
        )

        return project_member_update
