# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset


T = TypeVar("T", bound="ReleaseSummary")


@_attrs_define
class ReleaseSummary:
    """Part of `Release`.

    Attributes:
        features_count (int | Unset):  Default: 0.
        fixes_count (int | Unset):  Default: 0.
        breaking_changes_count (int | Unset):  Default: 0.
        total_commits (int | Unset):  Default: 0.
    """

    features_count: int | Unset = 0
    fixes_count: int | Unset = 0
    breaking_changes_count: int | Unset = 0
    total_commits: int | Unset = 0
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        features_count = self.features_count

        fixes_count = self.fixes_count

        breaking_changes_count = self.breaking_changes_count

        total_commits = self.total_commits

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if features_count is not UNSET:
            field_dict["features_count"] = features_count
        if fixes_count is not UNSET:
            field_dict["fixes_count"] = fixes_count
        if breaking_changes_count is not UNSET:
            field_dict["breaking_changes_count"] = breaking_changes_count
        if total_commits is not UNSET:
            field_dict["total_commits"] = total_commits

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        features_count = d.pop("features_count", UNSET)

        fixes_count = d.pop("fixes_count", UNSET)

        breaking_changes_count = d.pop("breaking_changes_count", UNSET)

        total_commits = d.pop("total_commits", UNSET)

        release_summary = cls(
            features_count=features_count,
            fixes_count=fixes_count,
            breaking_changes_count=breaking_changes_count,
            total_commits=total_commits,
        )

        release_summary.additional_properties = d
        return release_summary

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
