# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
    from ..models.review_token import ReviewToken


T = TypeVar("T", bound="ReviewMember")


@_attrs_define
class ReviewMember:
    """Part of `AccessReview`.

    Attributes:
        user_id (str):
        kind (str): `user` or `service_account`
        role (str):
        username (None | str | Unset):
        email (None | str | Unset):
        designation (None | str | Unset):
        last_active_at (None | str | Unset):
        tokens (list[ReviewToken] | Unset): Tokens that authenticate right now
    """

    user_id: str
    kind: str
    role: str
    username: None | str | Unset = UNSET
    email: None | str | Unset = UNSET
    designation: None | str | Unset = UNSET
    last_active_at: None | str | Unset = UNSET
    tokens: list[ReviewToken] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.review_token import ReviewToken  # noqa: PLC0415

        user_id = self.user_id

        kind = self.kind

        role = self.role

        username: None | str | Unset
        if isinstance(self.username, Unset):
            username = UNSET
        else:
            username = self.username

        email: None | str | Unset
        if isinstance(self.email, Unset):
            email = UNSET
        else:
            email = self.email

        designation: None | str | Unset
        if isinstance(self.designation, Unset):
            designation = UNSET
        else:
            designation = self.designation

        last_active_at: None | str | Unset
        if isinstance(self.last_active_at, Unset):
            last_active_at = UNSET
        else:
            last_active_at = self.last_active_at

        tokens: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.tokens, Unset):
            tokens = []
            for tokens_item_data in self.tokens:
                tokens_item = tokens_item_data.to_dict()
                tokens.append(tokens_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "user_id": user_id,
                "kind": kind,
                "role": role,
            }
        )
        if username is not UNSET:
            field_dict["username"] = username
        if email is not UNSET:
            field_dict["email"] = email
        if designation is not UNSET:
            field_dict["designation"] = designation
        if last_active_at is not UNSET:
            field_dict["last_active_at"] = last_active_at
        if tokens is not UNSET:
            field_dict["tokens"] = tokens

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.review_token import ReviewToken  # noqa: PLC0415

        d = dict(src_dict)
        user_id = d.pop("user_id")

        kind = d.pop("kind")

        role = d.pop("role")

        def _parse_username(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        username = _parse_username(d.pop("username", UNSET))

        def _parse_email(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        email = _parse_email(d.pop("email", UNSET))

        def _parse_designation(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        designation = _parse_designation(d.pop("designation", UNSET))

        def _parse_last_active_at(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        last_active_at = _parse_last_active_at(d.pop("last_active_at", UNSET))

        _tokens = d.pop("tokens", UNSET)
        tokens: list[ReviewToken] | Unset = UNSET
        if _tokens is not UNSET:
            tokens = []
            for tokens_item_data in _tokens:
                tokens_item = ReviewToken.from_dict(tokens_item_data)

                tokens.append(tokens_item)

        review_member = cls(
            user_id=user_id,
            kind=kind,
            role=role,
            username=username,
            email=email,
            designation=designation,
            last_active_at=last_active_at,
            tokens=tokens,
        )

        review_member.additional_properties = d
        return review_member

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
