# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.section_scope_enum import check_section_scope_enum
from ..models.section_scope_enum import SectionScopeEnum
from typing import cast


T = TypeVar("T", bound="SectionReorder")


@_attrs_define
class SectionReorder:
    """The request body of `sections.reorder`.

    Attributes:
        scope_type (SectionScopeEnum): One of `project`, `team`, `user`. Used by `ScopeRef` and 5 more.
        scope_id (str):
        section_ids (list[str]): Every section of the scope, in the new order
    """

    scope_type: SectionScopeEnum
    scope_id: str
    section_ids: list[str]
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        scope_type: str = self.scope_type

        scope_id = self.scope_id

        section_ids = self.section_ids

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "scope_type": scope_type,
                "scope_id": scope_id,
                "section_ids": section_ids,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        scope_type = check_section_scope_enum(d.pop("scope_type"))

        scope_id = d.pop("scope_id")

        section_ids = cast(list[str], d.pop("section_ids"))

        section_reorder = cls(
            scope_type=scope_type,
            scope_id=scope_id,
            section_ids=section_ids,
        )

        return section_reorder
