# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast


T = TypeVar("T", bound="ServiceAccountCreate")


@_attrs_define
class ServiceAccountCreate:
    """The request body of `service-accounts.create`.

    Attributes:
        name (str): What the account is for, e.g. `CI bot`
        designation (None | str | Unset): Optional designation (id, name or label), as for any member
    """

    name: str
    designation: None | str | Unset = UNSET
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        designation: None | str | Unset
        if isinstance(self.designation, Unset):
            designation = UNSET
        else:
            designation = self.designation

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "name": name,
            }
        )
        if designation is not UNSET:
            field_dict["designation"] = designation

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name")

        def _parse_designation(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        designation = _parse_designation(d.pop("designation", UNSET))

        service_account_create = cls(
            name=name,
            designation=designation,
        )

        return service_account_create
