# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.storage_file_kind import check_storage_file_kind
from ..models.storage_file_kind import StorageFileKind
from ..types import UNSET, Unset
from typing import cast


T = TypeVar("T", bound="StorageFile")


@_attrs_define
class StorageFile:
    """Part of `StorageUsage`.

    Attributes:
        kind (StorageFileKind):
        id (str): The attachment id (task / bug) or the resource id (project file)
        bytes_ (int):
        name (None | str | Unset):
        created_at (None | str | Unset):
        parent_id (None | str | Unset): The task (task), bug (bug) or project (project file) it belongs to
        project_id (None | str | Unset):
    """

    kind: StorageFileKind
    id: str
    bytes_: int
    name: None | str | Unset = UNSET
    created_at: None | str | Unset = UNSET
    parent_id: None | str | Unset = UNSET
    project_id: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        kind: str = self.kind

        id = self.id

        bytes_ = self.bytes_

        name: None | str | Unset
        if isinstance(self.name, Unset):
            name = UNSET
        else:
            name = self.name

        created_at: None | str | Unset
        if isinstance(self.created_at, Unset):
            created_at = UNSET
        else:
            created_at = self.created_at

        parent_id: None | str | Unset
        if isinstance(self.parent_id, Unset):
            parent_id = UNSET
        else:
            parent_id = self.parent_id

        project_id: None | str | Unset
        if isinstance(self.project_id, Unset):
            project_id = UNSET
        else:
            project_id = self.project_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "kind": kind,
                "id": id,
                "bytes": bytes_,
            }
        )
        if name is not UNSET:
            field_dict["name"] = name
        if created_at is not UNSET:
            field_dict["created_at"] = created_at
        if parent_id is not UNSET:
            field_dict["parent_id"] = parent_id
        if project_id is not UNSET:
            field_dict["project_id"] = project_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        kind = check_storage_file_kind(d.pop("kind"))

        id = d.pop("id")

        bytes_ = d.pop("bytes")

        def _parse_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        name = _parse_name(d.pop("name", UNSET))

        def _parse_created_at(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        created_at = _parse_created_at(d.pop("created_at", UNSET))

        def _parse_parent_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        parent_id = _parse_parent_id(d.pop("parent_id", UNSET))

        def _parse_project_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        project_id = _parse_project_id(d.pop("project_id", UNSET))

        storage_file = cls(
            kind=kind,
            id=id,
            bytes_=bytes_,
            name=name,
            created_at=created_at,
            parent_id=parent_id,
            project_id=project_id,
        )

        storage_file.additional_properties = d
        return storage_file

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
