# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.storage_usage_status import check_storage_usage_status
from ..models.storage_usage_status import StorageUsageStatus
from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
    from ..models.storage_breakdown import StorageBreakdown
    from ..models.storage_day import StorageDay
    from ..models.storage_file import StorageFile


T = TypeVar("T", bound="StorageUsage")


@_attrs_define
class StorageUsage:
    """Returned by `organizations.storage`.

    Attributes:
        org_id (str):
        bytes_used (int): Bytes of the organization's files right now (decimal: 1 GB = 10^9 bytes)
        file_count (int): Counted files (task attachments, project files, legacy bug attachments); `GET
            .../storage/files` lists them
        included_bytes (int): Storage included before overage, in bytes (decimal). The plan's value is 10^10 (10 GB); an
            organization may have its own.
        overage_bytes (int): max(0, bytes_used - included_bytes)
        percent (float): bytes_used / included_bytes, in percent, one decimal
        status (StorageUsageStatus): ok; warning (80 % or more); blocked (full, no payment method: new uploads answer
            402); metered (full, a payment method on file: billed per GB-month at month end); exempt (full, an internal
            organization that is never billed or blocked)
        payment_method_on_file (bool):
        billing_exempt (bool): An internal organization: metered and shown, never billed or blocked
        breakdown (StorageBreakdown): Part of `StorageUsage`.
        manage_url (str): The Storage and billing page in the web app
        project_count (int | Unset): Projects holding at least one counted file; `GET .../storage/projects` lists them
            Default: 0.
        top_files (list[StorageFile] | Unset): The 20 largest files (empty for a guest)
        trend (list[StorageDay] | Unset): The last 30 days, one row per day recorded
        updated_at (None | str | Unset): When the ledger last changed
    """

    org_id: str
    bytes_used: int
    file_count: int
    included_bytes: int
    overage_bytes: int
    percent: float
    status: StorageUsageStatus
    payment_method_on_file: bool
    billing_exempt: bool
    breakdown: StorageBreakdown
    manage_url: str
    project_count: int | Unset = 0
    top_files: list[StorageFile] | Unset = UNSET
    trend: list[StorageDay] | Unset = UNSET
    updated_at: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.storage_breakdown import StorageBreakdown  # noqa: PLC0415
        from ..models.storage_day import StorageDay  # noqa: PLC0415
        from ..models.storage_file import StorageFile  # noqa: PLC0415

        org_id = self.org_id

        bytes_used = self.bytes_used

        file_count = self.file_count

        included_bytes = self.included_bytes

        overage_bytes = self.overage_bytes

        percent = self.percent

        status: str = self.status

        payment_method_on_file = self.payment_method_on_file

        billing_exempt = self.billing_exempt

        breakdown = self.breakdown.to_dict()

        manage_url = self.manage_url

        project_count = self.project_count

        top_files: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.top_files, Unset):
            top_files = []
            for top_files_item_data in self.top_files:
                top_files_item = top_files_item_data.to_dict()
                top_files.append(top_files_item)

        trend: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.trend, Unset):
            trend = []
            for trend_item_data in self.trend:
                trend_item = trend_item_data.to_dict()
                trend.append(trend_item)

        updated_at: None | str | Unset
        if isinstance(self.updated_at, Unset):
            updated_at = UNSET
        else:
            updated_at = self.updated_at

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "org_id": org_id,
                "bytes_used": bytes_used,
                "file_count": file_count,
                "included_bytes": included_bytes,
                "overage_bytes": overage_bytes,
                "percent": percent,
                "status": status,
                "payment_method_on_file": payment_method_on_file,
                "billing_exempt": billing_exempt,
                "breakdown": breakdown,
                "manage_url": manage_url,
            }
        )
        if project_count is not UNSET:
            field_dict["project_count"] = project_count
        if top_files is not UNSET:
            field_dict["top_files"] = top_files
        if trend is not UNSET:
            field_dict["trend"] = trend
        if updated_at is not UNSET:
            field_dict["updated_at"] = updated_at

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.storage_breakdown import StorageBreakdown  # noqa: PLC0415
        from ..models.storage_day import StorageDay  # noqa: PLC0415
        from ..models.storage_file import StorageFile  # noqa: PLC0415

        d = dict(src_dict)
        org_id = d.pop("org_id")

        bytes_used = d.pop("bytes_used")

        file_count = d.pop("file_count")

        included_bytes = d.pop("included_bytes")

        overage_bytes = d.pop("overage_bytes")

        percent = d.pop("percent")

        status = check_storage_usage_status(d.pop("status"))

        payment_method_on_file = d.pop("payment_method_on_file")

        billing_exempt = d.pop("billing_exempt")

        breakdown = StorageBreakdown.from_dict(d.pop("breakdown"))

        manage_url = d.pop("manage_url")

        project_count = d.pop("project_count", UNSET)

        _top_files = d.pop("top_files", UNSET)
        top_files: list[StorageFile] | Unset = UNSET
        if _top_files is not UNSET:
            top_files = []
            for top_files_item_data in _top_files:
                top_files_item = StorageFile.from_dict(top_files_item_data)

                top_files.append(top_files_item)

        _trend = d.pop("trend", UNSET)
        trend: list[StorageDay] | Unset = UNSET
        if _trend is not UNSET:
            trend = []
            for trend_item_data in _trend:
                trend_item = StorageDay.from_dict(trend_item_data)

                trend.append(trend_item)

        def _parse_updated_at(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        updated_at = _parse_updated_at(d.pop("updated_at", UNSET))

        storage_usage = cls(
            org_id=org_id,
            bytes_used=bytes_used,
            file_count=file_count,
            included_bytes=included_bytes,
            overage_bytes=overage_bytes,
            percent=percent,
            status=status,
            payment_method_on_file=payment_method_on_file,
            billing_exempt=billing_exempt,
            breakdown=breakdown,
            manage_url=manage_url,
            project_count=project_count,
            top_files=top_files,
            trend=trend,
            updated_at=updated_at,
        )

        storage_usage.additional_properties = d
        return storage_usage

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
