# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

TaskReviewDecisionDecision = Literal["accept", "reject"]

TASK_REVIEW_DECISION_DECISION_VALUES: set[TaskReviewDecisionDecision] = {
    "accept",
    "reject",
}


def check_task_review_decision_decision(value: str) -> TaskReviewDecisionDecision:
    if value in TASK_REVIEW_DECISION_DECISION_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {TASK_REVIEW_DECISION_DECISION_VALUES!r}")
