# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
import datetime


T = TypeVar("T", bound="TaskAttachmentInDB")


@_attrs_define
class TaskAttachmentInDB:
    """Returned by `task-attachments.create`, `task-attachments.read` and `task-attachments.update`.

    Attributes:
        task_id (str): Task ID (text) Example: task-1234.
        attachment_id (str):
        title (None | str | Unset): Attachment title Example: Design Doc.
        name (None | str | Unset): Attachment file name Example: design.pdf.
        url (None | str | Unset): Attachment URL Example: https://example.com/design.pdf.
        uploaded_by (None | str | Unset): Who uploaded the attachment
        uploaded_at (datetime.datetime | None | Unset): When the attachment was uploaded
        deleted_at (datetime.datetime | None | Unset): When the attachment was deleted
        deleted_by (None | str | Unset): Who deleted the attachment
        is_inline (bool | None | Unset): Is the attachment inline? Default: False. Example: False.
        url_expires_at (datetime.datetime | None | Unset): When `url` stops working (null for a link that does not
            expire)
        content_type (None | str | Unset): The file's detected type
    """

    task_id: str
    attachment_id: str
    title: None | str | Unset = UNSET
    name: None | str | Unset = UNSET
    url: None | str | Unset = UNSET
    uploaded_by: None | str | Unset = UNSET
    uploaded_at: datetime.datetime | None | Unset = UNSET
    deleted_at: datetime.datetime | None | Unset = UNSET
    deleted_by: None | str | Unset = UNSET
    is_inline: bool | None | Unset = False
    url_expires_at: datetime.datetime | None | Unset = UNSET
    content_type: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        task_id = self.task_id

        attachment_id = self.attachment_id

        title: None | str | Unset
        if isinstance(self.title, Unset):
            title = UNSET
        else:
            title = self.title

        name: None | str | Unset
        if isinstance(self.name, Unset):
            name = UNSET
        else:
            name = self.name

        url: None | str | Unset
        if isinstance(self.url, Unset):
            url = UNSET
        else:
            url = self.url

        uploaded_by: None | str | Unset
        if isinstance(self.uploaded_by, Unset):
            uploaded_by = UNSET
        else:
            uploaded_by = self.uploaded_by

        uploaded_at: None | str | Unset
        if isinstance(self.uploaded_at, Unset):
            uploaded_at = UNSET
        elif isinstance(self.uploaded_at, datetime.datetime):
            uploaded_at = self.uploaded_at.isoformat()
        else:
            uploaded_at = self.uploaded_at

        deleted_at: None | str | Unset
        if isinstance(self.deleted_at, Unset):
            deleted_at = UNSET
        elif isinstance(self.deleted_at, datetime.datetime):
            deleted_at = self.deleted_at.isoformat()
        else:
            deleted_at = self.deleted_at

        deleted_by: None | str | Unset
        if isinstance(self.deleted_by, Unset):
            deleted_by = UNSET
        else:
            deleted_by = self.deleted_by

        is_inline: bool | None | Unset
        if isinstance(self.is_inline, Unset):
            is_inline = UNSET
        else:
            is_inline = self.is_inline

        url_expires_at: None | str | Unset
        if isinstance(self.url_expires_at, Unset):
            url_expires_at = UNSET
        elif isinstance(self.url_expires_at, datetime.datetime):
            url_expires_at = self.url_expires_at.isoformat()
        else:
            url_expires_at = self.url_expires_at

        content_type: None | str | Unset
        if isinstance(self.content_type, Unset):
            content_type = UNSET
        else:
            content_type = self.content_type

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "task_id": task_id,
                "attachment_id": attachment_id,
            }
        )
        if title is not UNSET:
            field_dict["title"] = title
        if name is not UNSET:
            field_dict["name"] = name
        if url is not UNSET:
            field_dict["url"] = url
        if uploaded_by is not UNSET:
            field_dict["uploaded_by"] = uploaded_by
        if uploaded_at is not UNSET:
            field_dict["uploaded_at"] = uploaded_at
        if deleted_at is not UNSET:
            field_dict["deleted_at"] = deleted_at
        if deleted_by is not UNSET:
            field_dict["deleted_by"] = deleted_by
        if is_inline is not UNSET:
            field_dict["is_inline"] = is_inline
        if url_expires_at is not UNSET:
            field_dict["url_expires_at"] = url_expires_at
        if content_type is not UNSET:
            field_dict["content_type"] = content_type

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        task_id = d.pop("task_id")

        attachment_id = d.pop("attachment_id")

        def _parse_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        title = _parse_title(d.pop("title", UNSET))

        def _parse_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        name = _parse_name(d.pop("name", UNSET))

        def _parse_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        url = _parse_url(d.pop("url", UNSET))

        def _parse_uploaded_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        uploaded_by = _parse_uploaded_by(d.pop("uploaded_by", UNSET))

        def _parse_uploaded_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                uploaded_at_type_0 = datetime.datetime.fromisoformat(data)

                return uploaded_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        uploaded_at = _parse_uploaded_at(d.pop("uploaded_at", UNSET))

        def _parse_deleted_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                deleted_at_type_0 = datetime.datetime.fromisoformat(data)

                return deleted_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        deleted_at = _parse_deleted_at(d.pop("deleted_at", UNSET))

        def _parse_deleted_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        deleted_by = _parse_deleted_by(d.pop("deleted_by", UNSET))

        def _parse_is_inline(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        is_inline = _parse_is_inline(d.pop("is_inline", UNSET))

        def _parse_url_expires_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                url_expires_at_type_0 = datetime.datetime.fromisoformat(data)

                return url_expires_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        url_expires_at = _parse_url_expires_at(d.pop("url_expires_at", UNSET))

        def _parse_content_type(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        content_type = _parse_content_type(d.pop("content_type", UNSET))

        task_attachment_in_db = cls(
            task_id=task_id,
            attachment_id=attachment_id,
            title=title,
            name=name,
            url=url,
            uploaded_by=uploaded_by,
            uploaded_at=uploaded_at,
            deleted_at=deleted_at,
            deleted_by=deleted_by,
            is_inline=is_inline,
            url_expires_at=url_expires_at,
            content_type=content_type,
        )

        task_attachment_in_db.additional_properties = d
        return task_attachment_in_db

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
