# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

TeamRoleEnum = Literal["member", "owner"]

TEAM_ROLE_ENUM_VALUES: set[TeamRoleEnum] = {
    "member",
    "owner",
}


def check_team_role_enum(value: str) -> TeamRoleEnum:
    if value in TEAM_ROLE_ENUM_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {TEAM_ROLE_ENUM_VALUES!r}")
