# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.view_scope_enum import check_view_scope_enum
from ..models.view_scope_enum import ViewScopeEnum
from ..types import UNSET, Unset
from typing import cast


T = TypeVar("T", bound="ViewDuplicate")


@_attrs_define
class ViewDuplicate:
    """The request body of `views.duplicate`.

    Attributes:
        scope_type (ViewScopeEnum | Unset): One of `user`, `team`, `project`. Used by `PinOut` and 3 more.
        scope_id (None | str | Unset):
        name (None | str | Unset): Defaults to '<name> (copy)'
    """

    scope_type: ViewScopeEnum | Unset = UNSET
    scope_id: None | str | Unset = UNSET
    name: None | str | Unset = UNSET
    # taskadence: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        scope_type: str | Unset = UNSET
        if not isinstance(self.scope_type, Unset):
            scope_type = self.scope_type

        scope_id: None | str | Unset
        if isinstance(self.scope_id, Unset):
            scope_id = UNSET
        else:
            scope_id = self.scope_id

        name: None | str | Unset
        if isinstance(self.name, Unset):
            name = UNSET
        else:
            name = self.name

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if scope_type is not UNSET:
            field_dict["scope_type"] = scope_type
        if scope_id is not UNSET:
            field_dict["scope_id"] = scope_id
        if name is not UNSET:
            field_dict["name"] = name

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _scope_type = d.pop("scope_type", UNSET)
        scope_type: ViewScopeEnum | Unset
        if isinstance(_scope_type, Unset):
            scope_type = UNSET
        else:
            scope_type = check_view_scope_enum(_scope_type)

        def _parse_scope_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        scope_id = _parse_scope_id(d.pop("scope_id", UNSET))

        def _parse_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        name = _parse_name(d.pop("name", UNSET))

        view_duplicate = cls(
            scope_type=scope_type,
            scope_id=scope_id,
            name=name,
        )

        return view_duplicate
