# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

WebhookUpdateStatusType0 = Literal["active", "paused"]

WEBHOOK_UPDATE_STATUS_TYPE_0_VALUES: set[WebhookUpdateStatusType0] = {
    "active",
    "paused",
}


def check_webhook_update_status_type_0(value: str) -> WebhookUpdateStatusType0:
    if value in WEBHOOK_UPDATE_STATUS_TYPE_0_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {WEBHOOK_UPDATE_STATUS_TYPE_0_VALUES!r}")
