# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

AgentTaskReviewEnum = Literal["always", "never", "private_projects"]

AGENT_TASK_REVIEW_ENUM_VALUES: set[AgentTaskReviewEnum] = {
    "always",
    "never",
    "private_projects",
}


def check_agent_task_review_enum(value: str) -> AgentTaskReviewEnum:
    if value in AGENT_TASK_REVIEW_ENUM_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {AGENT_TASK_REVIEW_ENUM_VALUES!r}")
