# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset


T = TypeVar("T", bound="GoalDeleted")


@_attrs_define
class GoalDeleted:
    """
    Attributes:
        ok (bool):
        goal_id (str):
        unfiled_tasks (int): Tasks the goal held; they stay in the project with `goal_id` null
    """

    ok: bool
    goal_id: str
    unfiled_tasks: int
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        ok = self.ok

        goal_id = self.goal_id

        unfiled_tasks = self.unfiled_tasks

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ok": ok,
                "goal_id": goal_id,
                "unfiled_tasks": unfiled_tasks,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        ok = d.pop("ok")

        goal_id = d.pop("goal_id")

        unfiled_tasks = d.pop("unfiled_tasks")

        goal_deleted = cls(
            ok=ok,
            goal_id=goal_id,
            unfiled_tasks=unfiled_tasks,
        )

        goal_deleted.additional_properties = d
        return goal_deleted

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
