# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

McpArtefactKind = Literal["command", "file", "settings"]

MCP_ARTEFACT_KIND_VALUES: set[McpArtefactKind] = {
    "command",
    "file",
    "settings",
}


def check_mcp_artefact_kind(value: str) -> McpArtefactKind:
    if value in MCP_ARTEFACT_KIND_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {MCP_ARTEFACT_KIND_VALUES!r}")
