# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

OAuthClientCreatedClientType = Literal["confidential", "public"]

O_AUTH_CLIENT_CREATED_CLIENT_TYPE_VALUES: set[OAuthClientCreatedClientType] = {
    "confidential",
    "public",
}


def check_o_auth_client_created_client_type(value: str) -> OAuthClientCreatedClientType:
    if value in O_AUTH_CLIENT_CREATED_CLIENT_TYPE_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {O_AUTH_CLIENT_CREATED_CLIENT_TYPE_VALUES!r}")
