# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.pin_type_enum import check_pin_type_enum
from ..models.pin_type_enum import PinTypeEnum
from typing import cast


T = TypeVar("T", bound="PinRef")


@_attrs_define
class PinRef:
    """Part of `PinOrder`.

    Attributes:
        pin_type (PinTypeEnum): One of `view`, `project`. Used by `PinOut` and 1 more.
        pin_id (str):
    """

    pin_type: PinTypeEnum
    pin_id: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        pin_type: str = self.pin_type

        pin_id = self.pin_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "pin_type": pin_type,
                "pin_id": pin_id,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        pin_type = check_pin_type_enum(d.pop("pin_type"))

        pin_id = d.pop("pin_id")

        pin_ref = cls(
            pin_type=pin_type,
            pin_id=pin_id,
        )

        pin_ref.additional_properties = d
        return pin_ref

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
