# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
    from ..models.goal_out import GoalOut


T = TypeVar("T", bound="ProjectGoalsOut")


@_attrs_define
class ProjectGoalsOut:
    """`GET /v1/projects/{project_id}/goals`: the project's live goals by position, plus project-level sums that count only
    the tasks filed under its goals.

        Attributes:
            project_id (str):
            data (list[GoalOut]):
            next_cursor (None | str | Unset): The next page's cursor; null on the last page.
            goals_tasks_total (int | Unset):  Default: 0.
            goals_tasks_completed (int | Unset):  Default: 0.
    """

    project_id: str
    data: list[GoalOut]
    next_cursor: None | str | Unset = UNSET
    goals_tasks_total: int | Unset = 0
    goals_tasks_completed: int | Unset = 0
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.goal_out import GoalOut  # noqa: PLC0415

        project_id = self.project_id

        data = []
        for data_item_data in self.data:
            data_item = data_item_data.to_dict()
            data.append(data_item)

        next_cursor: None | str | Unset
        if isinstance(self.next_cursor, Unset):
            next_cursor = UNSET
        else:
            next_cursor = self.next_cursor

        goals_tasks_total = self.goals_tasks_total

        goals_tasks_completed = self.goals_tasks_completed

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "project_id": project_id,
                "data": data,
            }
        )
        if next_cursor is not UNSET:
            field_dict["next_cursor"] = next_cursor
        if goals_tasks_total is not UNSET:
            field_dict["goals_tasks_total"] = goals_tasks_total
        if goals_tasks_completed is not UNSET:
            field_dict["goals_tasks_completed"] = goals_tasks_completed

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.goal_out import GoalOut  # noqa: PLC0415

        d = dict(src_dict)
        project_id = d.pop("project_id")

        data = []
        _data = d.pop("data")
        for data_item_data in _data:
            data_item = GoalOut.from_dict(data_item_data)

            data.append(data_item)

        def _parse_next_cursor(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        next_cursor = _parse_next_cursor(d.pop("next_cursor", UNSET))

        goals_tasks_total = d.pop("goals_tasks_total", UNSET)

        goals_tasks_completed = d.pop("goals_tasks_completed", UNSET)

        project_goals_out = cls(
            project_id=project_id,
            data=data,
            next_cursor=next_cursor,
            goals_tasks_total=goals_tasks_total,
            goals_tasks_completed=goals_tasks_completed,
        )

        project_goals_out.additional_properties = d
        return project_goals_out

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
