# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from typing import Literal

RegistrationErrorBodyError = Literal["invalid_client_metadata", "invalid_redirect_uri"]

REGISTRATION_ERROR_BODY_ERROR_VALUES: set[RegistrationErrorBodyError] = {
    "invalid_client_metadata",
    "invalid_redirect_uri",
}


def check_registration_error_body_error(value: str) -> RegistrationErrorBodyError:
    if value in REGISTRATION_ERROR_BODY_ERROR_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {REGISTRATION_ERROR_BODY_ERROR_VALUES!r}")
