# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.environment import check_environment
from ..models.environment import Environment
from ..models.release_type import check_release_type
from ..models.release_type import ReleaseType
from ..types import UNSET, Unset
from typing import cast
import datetime

if TYPE_CHECKING:
    from ..models.release_note_item import ReleaseNoteItem
    from ..models.release_summary import ReleaseSummary


T = TypeVar("T", bound="Release")


@_attrs_define
class Release:
    """Part of `WhatsNewResponse`.

    Attributes:
        id (str):
        version (str):
        tag_name (str):
        release_type (ReleaseType): One of `major`, `minor`, `patch`, `prerelease`. Used by `Release`.
        environment (Environment): One of `development`, `uat`, `production`. Used by `Release`.
        repository (str):
        commit_sha (str):
        branch (str):
        release_date (datetime.datetime):
        created_at (datetime.datetime):
        updated_at (datetime.datetime):
        summary (ReleaseSummary): Part of `Release`.
        is_prerelease (bool | Unset):  Default: False.
        is_draft (bool | Unset):  Default: False.
        release_notes (list[ReleaseNoteItem] | Unset):
    """

    id: str
    version: str
    tag_name: str
    release_type: ReleaseType
    environment: Environment
    repository: str
    commit_sha: str
    branch: str
    release_date: datetime.datetime
    created_at: datetime.datetime
    updated_at: datetime.datetime
    summary: ReleaseSummary
    is_prerelease: bool | Unset = False
    is_draft: bool | Unset = False
    release_notes: list[ReleaseNoteItem] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.release_note_item import ReleaseNoteItem  # noqa: PLC0415
        from ..models.release_summary import ReleaseSummary  # noqa: PLC0415

        id = self.id

        version = self.version

        tag_name = self.tag_name

        release_type: str = self.release_type

        environment: str = self.environment

        repository = self.repository

        commit_sha = self.commit_sha

        branch = self.branch

        release_date = self.release_date.isoformat()

        created_at = self.created_at.isoformat()

        updated_at = self.updated_at.isoformat()

        summary = self.summary.to_dict()

        is_prerelease = self.is_prerelease

        is_draft = self.is_draft

        release_notes: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.release_notes, Unset):
            release_notes = []
            for release_notes_item_data in self.release_notes:
                release_notes_item = release_notes_item_data.to_dict()
                release_notes.append(release_notes_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "version": version,
                "tag_name": tag_name,
                "release_type": release_type,
                "environment": environment,
                "repository": repository,
                "commit_sha": commit_sha,
                "branch": branch,
                "release_date": release_date,
                "created_at": created_at,
                "updated_at": updated_at,
                "summary": summary,
            }
        )
        if is_prerelease is not UNSET:
            field_dict["is_prerelease"] = is_prerelease
        if is_draft is not UNSET:
            field_dict["is_draft"] = is_draft
        if release_notes is not UNSET:
            field_dict["release_notes"] = release_notes

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.release_note_item import ReleaseNoteItem  # noqa: PLC0415
        from ..models.release_summary import ReleaseSummary  # noqa: PLC0415

        d = dict(src_dict)
        id = d.pop("id")

        version = d.pop("version")

        tag_name = d.pop("tag_name")

        release_type = check_release_type(d.pop("release_type"))

        environment = check_environment(d.pop("environment"))

        repository = d.pop("repository")

        commit_sha = d.pop("commit_sha")

        branch = d.pop("branch")

        release_date = datetime.datetime.fromisoformat(d.pop("release_date"))

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))

        updated_at = datetime.datetime.fromisoformat(d.pop("updated_at"))

        summary = ReleaseSummary.from_dict(d.pop("summary"))

        is_prerelease = d.pop("is_prerelease", UNSET)

        is_draft = d.pop("is_draft", UNSET)

        _release_notes = d.pop("release_notes", UNSET)
        release_notes: list[ReleaseNoteItem] | Unset = UNSET
        if _release_notes is not UNSET:
            release_notes = []
            for release_notes_item_data in _release_notes:
                release_notes_item = ReleaseNoteItem.from_dict(release_notes_item_data)

                release_notes.append(release_notes_item)

        release = cls(
            id=id,
            version=version,
            tag_name=tag_name,
            release_type=release_type,
            environment=environment,
            repository=repository,
            commit_sha=commit_sha,
            branch=branch,
            release_date=release_date,
            created_at=created_at,
            updated_at=updated_at,
            summary=summary,
            is_prerelease=is_prerelease,
            is_draft=is_draft,
            release_notes=release_notes,
        )

        release.additional_properties = d
        return release

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
