# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.commit_type import check_commit_type
from ..models.commit_type import CommitType
from ..types import UNSET, Unset
from typing import cast
import datetime


T = TypeVar("T", bound="ReleaseNoteItem")


@_attrs_define
class ReleaseNoteItem:
    """
    Attributes:
        id (str):
        commit_sha (str):
        commit_type (CommitType):
        subject (str):
        commit_date (datetime.datetime):
        scope (None | str | Unset):
        body (None | str | Unset):
        breaking_change (bool | Unset):  Default: False.
        breaking_change_description (None | str | Unset):
        author_name (None | str | Unset):
        author_email (None | str | Unset):
        pr_number (int | None | Unset):
        pr_title (None | str | Unset):
        pr_url (None | str | Unset):
    """

    id: str
    commit_sha: str
    commit_type: CommitType
    subject: str
    commit_date: datetime.datetime
    scope: None | str | Unset = UNSET
    body: None | str | Unset = UNSET
    breaking_change: bool | Unset = False
    breaking_change_description: None | str | Unset = UNSET
    author_name: None | str | Unset = UNSET
    author_email: None | str | Unset = UNSET
    pr_number: int | None | Unset = UNSET
    pr_title: None | str | Unset = UNSET
    pr_url: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        commit_sha = self.commit_sha

        commit_type: str = self.commit_type

        subject = self.subject

        commit_date = self.commit_date.isoformat()

        scope: None | str | Unset
        if isinstance(self.scope, Unset):
            scope = UNSET
        else:
            scope = self.scope

        body: None | str | Unset
        if isinstance(self.body, Unset):
            body = UNSET
        else:
            body = self.body

        breaking_change = self.breaking_change

        breaking_change_description: None | str | Unset
        if isinstance(self.breaking_change_description, Unset):
            breaking_change_description = UNSET
        else:
            breaking_change_description = self.breaking_change_description

        author_name: None | str | Unset
        if isinstance(self.author_name, Unset):
            author_name = UNSET
        else:
            author_name = self.author_name

        author_email: None | str | Unset
        if isinstance(self.author_email, Unset):
            author_email = UNSET
        else:
            author_email = self.author_email

        pr_number: int | None | Unset
        if isinstance(self.pr_number, Unset):
            pr_number = UNSET
        else:
            pr_number = self.pr_number

        pr_title: None | str | Unset
        if isinstance(self.pr_title, Unset):
            pr_title = UNSET
        else:
            pr_title = self.pr_title

        pr_url: None | str | Unset
        if isinstance(self.pr_url, Unset):
            pr_url = UNSET
        else:
            pr_url = self.pr_url

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "commit_sha": commit_sha,
                "commit_type": commit_type,
                "subject": subject,
                "commit_date": commit_date,
            }
        )
        if scope is not UNSET:
            field_dict["scope"] = scope
        if body is not UNSET:
            field_dict["body"] = body
        if breaking_change is not UNSET:
            field_dict["breaking_change"] = breaking_change
        if breaking_change_description is not UNSET:
            field_dict["breaking_change_description"] = breaking_change_description
        if author_name is not UNSET:
            field_dict["author_name"] = author_name
        if author_email is not UNSET:
            field_dict["author_email"] = author_email
        if pr_number is not UNSET:
            field_dict["pr_number"] = pr_number
        if pr_title is not UNSET:
            field_dict["pr_title"] = pr_title
        if pr_url is not UNSET:
            field_dict["pr_url"] = pr_url

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        commit_sha = d.pop("commit_sha")

        commit_type = check_commit_type(d.pop("commit_type"))

        subject = d.pop("subject")

        commit_date = datetime.datetime.fromisoformat(d.pop("commit_date"))

        def _parse_scope(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        scope = _parse_scope(d.pop("scope", UNSET))

        def _parse_body(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        body = _parse_body(d.pop("body", UNSET))

        breaking_change = d.pop("breaking_change", UNSET)

        def _parse_breaking_change_description(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        breaking_change_description = _parse_breaking_change_description(d.pop("breaking_change_description", UNSET))

        def _parse_author_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        author_name = _parse_author_name(d.pop("author_name", UNSET))

        def _parse_author_email(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        author_email = _parse_author_email(d.pop("author_email", UNSET))

        def _parse_pr_number(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        pr_number = _parse_pr_number(d.pop("pr_number", UNSET))

        def _parse_pr_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        pr_title = _parse_pr_title(d.pop("pr_title", UNSET))

        def _parse_pr_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        pr_url = _parse_pr_url(d.pop("pr_url", UNSET))

        release_note_item = cls(
            id=id,
            commit_sha=commit_sha,
            commit_type=commit_type,
            subject=subject,
            commit_date=commit_date,
            scope=scope,
            body=body,
            breaking_change=breaking_change,
            breaking_change_description=breaking_change_description,
            author_name=author_name,
            author_email=author_email,
            pr_number=pr_number,
            pr_title=pr_title,
            pr_url=pr_url,
        )

        release_note_item.additional_properties = d
        return release_note_item

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
