# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
import datetime


T = TypeVar("T", bound="RoadmapStopOut")


@_attrs_define
class RoadmapStopOut:
    """
    Attributes:
        stop_id (str):
        project_id (str):
        title (str):
        position (int): Its position on THIS journey (a junction has one per line).
        done (int): Distinct visible tasks that are `completed`.
        total (int): Distinct visible tasks — direct ∪ through pinned milestones, deduped by task_id.
        journey_ids (list[str]): Every live line this stop is on; two or more = a junction.
        target_date (datetime.date | None | Unset):
        description (None | str | Unset):
        milestone_ids (list[str] | Unset): Live team milestones pinned to it.
    """

    stop_id: str
    project_id: str
    title: str
    position: int
    done: int
    total: int
    journey_ids: list[str]
    target_date: datetime.date | None | Unset = UNSET
    description: None | str | Unset = UNSET
    milestone_ids: list[str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        stop_id = self.stop_id

        project_id = self.project_id

        title = self.title

        position = self.position

        done = self.done

        total = self.total

        journey_ids = self.journey_ids

        target_date: None | str | Unset
        if isinstance(self.target_date, Unset):
            target_date = UNSET
        elif isinstance(self.target_date, datetime.date):
            target_date = self.target_date.isoformat()
        else:
            target_date = self.target_date

        description: None | str | Unset
        if isinstance(self.description, Unset):
            description = UNSET
        else:
            description = self.description

        milestone_ids: list[str] | Unset = UNSET
        if not isinstance(self.milestone_ids, Unset):
            milestone_ids = self.milestone_ids

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "stop_id": stop_id,
                "project_id": project_id,
                "title": title,
                "position": position,
                "done": done,
                "total": total,
                "journey_ids": journey_ids,
            }
        )
        if target_date is not UNSET:
            field_dict["target_date"] = target_date
        if description is not UNSET:
            field_dict["description"] = description
        if milestone_ids is not UNSET:
            field_dict["milestone_ids"] = milestone_ids

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        stop_id = d.pop("stop_id")

        project_id = d.pop("project_id")

        title = d.pop("title")

        position = d.pop("position")

        done = d.pop("done")

        total = d.pop("total")

        journey_ids = cast(list[str], d.pop("journey_ids"))

        def _parse_target_date(data: object) -> datetime.date | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                target_date_type_0 = datetime.date.fromisoformat(data)

                return target_date_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.date | None | Unset, data)

        target_date = _parse_target_date(d.pop("target_date", UNSET))

        def _parse_description(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        description = _parse_description(d.pop("description", UNSET))

        milestone_ids = cast(list[str], d.pop("milestone_ids", UNSET))

        roadmap_stop_out = cls(
            stop_id=stop_id,
            project_id=project_id,
            title=title,
            position=position,
            done=done,
            total=total,
            journey_ids=journey_ids,
            target_date=target_date,
            description=description,
            milestone_ids=milestone_ids,
        )

        roadmap_stop_out.additional_properties = d
        return roadmap_stop_out

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
