# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast

if TYPE_CHECKING:
    from ..models.roadmap_project_out import RoadmapProjectOut
    from ..models.roadmap_project_ref import RoadmapProjectRef


T = TypeVar("T", bound="RoadmapOut")


@_attrs_define
class RoadmapOut:
    """A roadmap. A team's roadmap and a project's roadmap share this shape.

    Attributes:
        projects (list[RoadmapProjectOut]):
        projects_without_roadmap (list[RoadmapProjectRef]):
    """

    projects: list[RoadmapProjectOut]
    projects_without_roadmap: list[RoadmapProjectRef]
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.roadmap_project_out import RoadmapProjectOut  # noqa: PLC0415
        from ..models.roadmap_project_ref import RoadmapProjectRef  # noqa: PLC0415

        projects = []
        for projects_item_data in self.projects:
            projects_item = projects_item_data.to_dict()
            projects.append(projects_item)

        projects_without_roadmap = []
        for projects_without_roadmap_item_data in self.projects_without_roadmap:
            projects_without_roadmap_item = projects_without_roadmap_item_data.to_dict()
            projects_without_roadmap.append(projects_without_roadmap_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "projects": projects,
                "projects_without_roadmap": projects_without_roadmap,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.roadmap_project_out import RoadmapProjectOut  # noqa: PLC0415
        from ..models.roadmap_project_ref import RoadmapProjectRef  # noqa: PLC0415

        d = dict(src_dict)
        projects = []
        _projects = d.pop("projects")
        for projects_item_data in _projects:
            projects_item = RoadmapProjectOut.from_dict(projects_item_data)

            projects.append(projects_item)

        projects_without_roadmap = []
        _projects_without_roadmap = d.pop("projects_without_roadmap")
        for projects_without_roadmap_item_data in _projects_without_roadmap:
            projects_without_roadmap_item = RoadmapProjectRef.from_dict(projects_without_roadmap_item_data)

            projects_without_roadmap.append(projects_without_roadmap_item)

        roadmap_out = cls(
            projects=projects,
            projects_without_roadmap=projects_without_roadmap,
        )

        roadmap_out.additional_properties = d
        return roadmap_out

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
