# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
import datetime


T = TypeVar("T", bound="SprintCreate")


@_attrs_define
class SprintCreate:
    """The request body of `sprints.create`.

    Attributes:
        name (str): Unique among the team's active sprints (case-insensitive) — 409 otherwise
        start_date (datetime.date): First day of the time box
        description (None | str | Unset):
        goal (None | str | Unset): What the sprint is for, in the team's words. Free text; nothing is derived from it.
        end_date (datetime.date | None | Unset): Last day of the time box (inclusive). Exactly one of `end_date` /
            `duration_weeks` is required; both is a 422.
        duration_weeks (int | None | Unset): Convenience: the end date is derived as start + 7*weeks - 1. The server
            stores the END DATE, never this.
    """

    name: str
    start_date: datetime.date
    description: None | str | Unset = UNSET
    goal: None | str | Unset = UNSET
    end_date: datetime.date | None | Unset = UNSET
    duration_weeks: int | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        start_date = self.start_date.isoformat()

        description: None | str | Unset
        if isinstance(self.description, Unset):
            description = UNSET
        else:
            description = self.description

        goal: None | str | Unset
        if isinstance(self.goal, Unset):
            goal = UNSET
        else:
            goal = self.goal

        end_date: None | str | Unset
        if isinstance(self.end_date, Unset):
            end_date = UNSET
        elif isinstance(self.end_date, datetime.date):
            end_date = self.end_date.isoformat()
        else:
            end_date = self.end_date

        duration_weeks: int | None | Unset
        if isinstance(self.duration_weeks, Unset):
            duration_weeks = UNSET
        else:
            duration_weeks = self.duration_weeks

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "name": name,
                "start_date": start_date,
            }
        )
        if description is not UNSET:
            field_dict["description"] = description
        if goal is not UNSET:
            field_dict["goal"] = goal
        if end_date is not UNSET:
            field_dict["end_date"] = end_date
        if duration_weeks is not UNSET:
            field_dict["duration_weeks"] = duration_weeks

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name")

        start_date = datetime.date.fromisoformat(d.pop("start_date"))

        def _parse_description(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        description = _parse_description(d.pop("description", UNSET))

        def _parse_goal(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        goal = _parse_goal(d.pop("goal", UNSET))

        def _parse_end_date(data: object) -> datetime.date | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                end_date_type_0 = datetime.date.fromisoformat(data)

                return end_date_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.date | None | Unset, data)

        end_date = _parse_end_date(d.pop("end_date", UNSET))

        def _parse_duration_weeks(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        duration_weeks = _parse_duration_weeks(d.pop("duration_weeks", UNSET))

        sprint_create = cls(
            name=name,
            start_date=start_date,
            description=description,
            goal=goal,
            end_date=end_date,
            duration_weeks=duration_weeks,
        )

        sprint_create.additional_properties = d
        return sprint_create

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
