# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.priority_enum import check_priority_enum
from ..models.priority_enum import PriorityEnum
from ..models.task_status_enum import check_task_status_enum
from ..models.task_status_enum import TaskStatusEnum
from ..models.task_type_enum import check_task_type_enum
from ..models.task_type_enum import TaskTypeEnum
from ..types import UNSET, Unset
from typing import cast
import datetime

if TYPE_CHECKING:
    from ..models.task_update_metadata_type_0_item import TaskUpdateMetadataType0Item
    from ..models.task_update_type_data_type_0 import TaskUpdateTypeDataType0


T = TypeVar("T", bound="TaskUpdate")


@_attrs_define
class TaskUpdate:
    """`PUT /tasks/{id}` body — a TRUE partial (3.15). Until 3.15 this was `pass`, so it inherited
    `title: str = Field(...)` and any body without a title was a 422 before the route ran (the goal
    card's `{"type_data": {...}}` write among them). Every field is optional here, `title` included;
    the route sends `dict(exclude_unset=True)` on, so an absent field is absent from the write and the
    base model's defaults never ride along. An EXPLICIT empty / whitespace-only title is still refused —
    "absent" and "blank" are different things. `TaskCreate` is unchanged: a task needs a title to exist.

        Attributes:
            project_id (None | str | Unset): Project ID (text) Example: project-1234.
            org_id (None | str | Unset): Organization ID (text) Example: org-1234.
            sub_tasks (list[str] | None | Unset): List of sub-task IDs Example: ['task-5678'].
            dependencies (list[str] | None | Unset): List of dependency task IDs Example: ['task-4321'].
            title (None | str | Unset): Task title. Omit to leave it; an explicit blank is refused (422). Example: Implement
                Login.
            description (None | str | Unset): Task description Example: Implement OAuth2 login flow..
            status (None | TaskStatusEnum | Unset): Task status Example: not_started.
            assignee (None | str | Unset): Assignee user name
            start_date (datetime.date | None | Unset): Start date Example: 2024-07-31.
            due_date (datetime.date | None | Unset): Due date Example: 2024-08-01.
            priority (None | PriorityEnum | Unset): Task priority Example: high.
            task_type (None | TaskTypeEnum | Unset): Kind of row (3.3): task (default) · bug · agent. A label, not a
                permission. 6.12: `goal` is retired — a goal is a project container (`goal_id`), not a task type. Example: task.
            tags (list[str] | None | Unset): List of tags Example: ['backend', 'auth'].
            type_data (None | TaskUpdateTypeDataType0 | Unset): Per-type extras (3.4). Bug keys: bug_status, bug_kind,
                environment, steps_to_reproduce, expected_result, actual_result, recommendation (writable); legacy_bug_id,
                tracker_id, reporter, estimated_time, actual_time, closed_at (response only). A write merges; null removes a
                key. 6.12: the goal keys (goal_*, legacy_goal_*) are retired — refused on write (422 naming the key), omitted
                from responses.
            metadata (list[TaskUpdateMetadataType0Item] | None | Unset): Additional metadata Example: [{'field': 'status',
                'new': 'in_progress', 'old': 'not_started'}].
            created_by (None | str | Unset): Who created the task
            updated_by (None | str | Unset): Who last updated the task
            is_subtask (bool | None | Unset): Is Sub Task
            bug_id (None | str | Unset): Bug ID (text) Example: B1234.
            tracker_id (None | str | Unset): On create (3.13): the sprint to file a bug under (`test_trackers.tracker_id`);
                refused (422) for a non-bug or a sprint of another project. Re-file through PUT /tasks/{id}/test-run. Example:
                TR1234.
            restricted_to (list[str] | None | Unset): Usernames allowed on this task (empty = everyone with membership). The
                API contract stays usernames in and out; since 2.2b the server also keeps `restricted_to_user_ids` (response
                only).
            team_id (None | str | Unset): Team the task is filed under (2.6a). Unfiled + team = that team's Intake. null =
                none.
            sprint_id (None | str | Unset): Team sprint this task is filed into (6.3, `team_sprints.sprint_id`). One per
                task; refused (422) unless the task is reachable from the sprint's team. null = none. Example: SP12345.
            milestone_id (None | str | Unset): Team milestone this task is filed under (6.5,
                `team_milestones.milestone_id`). One per task, independent of `sprint_id`; refused (422) unless the task is
                reachable from the milestone's team. null = none. Example: MS12345.
            goal_id (None | str | Unset): Project goal this task is filed under (6.12, `project_goals.goal_id`). One per
                task; refused (422) unless it is a live goal of the task's own project. A move to another project clears it.
                null = none. Example: G12345.
    """

    project_id: None | str | Unset = UNSET
    org_id: None | str | Unset = UNSET
    sub_tasks: list[str] | None | Unset = UNSET
    dependencies: list[str] | None | Unset = UNSET
    title: None | str | Unset = UNSET
    description: None | str | Unset = UNSET
    status: None | TaskStatusEnum | Unset = UNSET
    assignee: None | str | Unset = UNSET
    start_date: datetime.date | None | Unset = UNSET
    due_date: datetime.date | None | Unset = UNSET
    priority: None | PriorityEnum | Unset = UNSET
    task_type: None | TaskTypeEnum | Unset = UNSET
    tags: list[str] | None | Unset = UNSET
    type_data: None | TaskUpdateTypeDataType0 | Unset = UNSET
    metadata: list[TaskUpdateMetadataType0Item] | None | Unset = UNSET
    created_by: None | str | Unset = UNSET
    updated_by: None | str | Unset = UNSET
    is_subtask: bool | None | Unset = UNSET
    bug_id: None | str | Unset = UNSET
    tracker_id: None | str | Unset = UNSET
    restricted_to: list[str] | None | Unset = UNSET
    team_id: None | str | Unset = UNSET
    sprint_id: None | str | Unset = UNSET
    milestone_id: None | str | Unset = UNSET
    goal_id: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        from ..models.task_update_metadata_type_0_item import TaskUpdateMetadataType0Item  # noqa: PLC0415
        from ..models.task_update_type_data_type_0 import TaskUpdateTypeDataType0  # noqa: PLC0415

        project_id: None | str | Unset
        if isinstance(self.project_id, Unset):
            project_id = UNSET
        else:
            project_id = self.project_id

        org_id: None | str | Unset
        if isinstance(self.org_id, Unset):
            org_id = UNSET
        else:
            org_id = self.org_id

        sub_tasks: list[str] | None | Unset
        if isinstance(self.sub_tasks, Unset):
            sub_tasks = UNSET
        elif isinstance(self.sub_tasks, list):
            sub_tasks = self.sub_tasks

        else:
            sub_tasks = self.sub_tasks

        dependencies: list[str] | None | Unset
        if isinstance(self.dependencies, Unset):
            dependencies = UNSET
        elif isinstance(self.dependencies, list):
            dependencies = self.dependencies

        else:
            dependencies = self.dependencies

        title: None | str | Unset
        if isinstance(self.title, Unset):
            title = UNSET
        else:
            title = self.title

        description: None | str | Unset
        if isinstance(self.description, Unset):
            description = UNSET
        else:
            description = self.description

        status: None | str | Unset
        if isinstance(self.status, Unset):
            status = UNSET
        elif isinstance(self.status, str):
            status = self.status
        else:
            status = self.status

        assignee: None | str | Unset
        if isinstance(self.assignee, Unset):
            assignee = UNSET
        else:
            assignee = self.assignee

        start_date: None | str | Unset
        if isinstance(self.start_date, Unset):
            start_date = UNSET
        elif isinstance(self.start_date, datetime.date):
            start_date = self.start_date.isoformat()
        else:
            start_date = self.start_date

        due_date: None | str | Unset
        if isinstance(self.due_date, Unset):
            due_date = UNSET
        elif isinstance(self.due_date, datetime.date):
            due_date = self.due_date.isoformat()
        else:
            due_date = self.due_date

        priority: None | str | Unset
        if isinstance(self.priority, Unset):
            priority = UNSET
        elif isinstance(self.priority, str):
            priority = self.priority
        else:
            priority = self.priority

        task_type: None | str | Unset
        if isinstance(self.task_type, Unset):
            task_type = UNSET
        elif isinstance(self.task_type, str):
            task_type = self.task_type
        else:
            task_type = self.task_type

        tags: list[str] | None | Unset
        if isinstance(self.tags, Unset):
            tags = UNSET
        elif isinstance(self.tags, list):
            tags = self.tags

        else:
            tags = self.tags

        type_data: dict[str, Any] | None | Unset
        if isinstance(self.type_data, Unset):
            type_data = UNSET
        elif isinstance(self.type_data, TaskUpdateTypeDataType0):
            type_data = self.type_data.to_dict()
        else:
            type_data = self.type_data

        metadata: list[dict[str, Any]] | None | Unset
        if isinstance(self.metadata, Unset):
            metadata = UNSET
        elif isinstance(self.metadata, list):
            metadata = []
            for metadata_type_0_item_data in self.metadata:
                metadata_type_0_item = metadata_type_0_item_data.to_dict()
                metadata.append(metadata_type_0_item)

        else:
            metadata = self.metadata

        created_by: None | str | Unset
        if isinstance(self.created_by, Unset):
            created_by = UNSET
        else:
            created_by = self.created_by

        updated_by: None | str | Unset
        if isinstance(self.updated_by, Unset):
            updated_by = UNSET
        else:
            updated_by = self.updated_by

        is_subtask: bool | None | Unset
        if isinstance(self.is_subtask, Unset):
            is_subtask = UNSET
        else:
            is_subtask = self.is_subtask

        bug_id: None | str | Unset
        if isinstance(self.bug_id, Unset):
            bug_id = UNSET
        else:
            bug_id = self.bug_id

        tracker_id: None | str | Unset
        if isinstance(self.tracker_id, Unset):
            tracker_id = UNSET
        else:
            tracker_id = self.tracker_id

        restricted_to: list[str] | None | Unset
        if isinstance(self.restricted_to, Unset):
            restricted_to = UNSET
        elif isinstance(self.restricted_to, list):
            restricted_to = self.restricted_to

        else:
            restricted_to = self.restricted_to

        team_id: None | str | Unset
        if isinstance(self.team_id, Unset):
            team_id = UNSET
        else:
            team_id = self.team_id

        sprint_id: None | str | Unset
        if isinstance(self.sprint_id, Unset):
            sprint_id = UNSET
        else:
            sprint_id = self.sprint_id

        milestone_id: None | str | Unset
        if isinstance(self.milestone_id, Unset):
            milestone_id = UNSET
        else:
            milestone_id = self.milestone_id

        goal_id: None | str | Unset
        if isinstance(self.goal_id, Unset):
            goal_id = UNSET
        else:
            goal_id = self.goal_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if project_id is not UNSET:
            field_dict["project_id"] = project_id
        if org_id is not UNSET:
            field_dict["org_id"] = org_id
        if sub_tasks is not UNSET:
            field_dict["sub_tasks"] = sub_tasks
        if dependencies is not UNSET:
            field_dict["dependencies"] = dependencies
        if title is not UNSET:
            field_dict["title"] = title
        if description is not UNSET:
            field_dict["description"] = description
        if status is not UNSET:
            field_dict["status"] = status
        if assignee is not UNSET:
            field_dict["assignee"] = assignee
        if start_date is not UNSET:
            field_dict["start_date"] = start_date
        if due_date is not UNSET:
            field_dict["due_date"] = due_date
        if priority is not UNSET:
            field_dict["priority"] = priority
        if task_type is not UNSET:
            field_dict["task_type"] = task_type
        if tags is not UNSET:
            field_dict["tags"] = tags
        if type_data is not UNSET:
            field_dict["type_data"] = type_data
        if metadata is not UNSET:
            field_dict["metadata"] = metadata
        if created_by is not UNSET:
            field_dict["created_by"] = created_by
        if updated_by is not UNSET:
            field_dict["updated_by"] = updated_by
        if is_subtask is not UNSET:
            field_dict["is_subtask"] = is_subtask
        if bug_id is not UNSET:
            field_dict["bug_id"] = bug_id
        if tracker_id is not UNSET:
            field_dict["tracker_id"] = tracker_id
        if restricted_to is not UNSET:
            field_dict["restricted_to"] = restricted_to
        if team_id is not UNSET:
            field_dict["team_id"] = team_id
        if sprint_id is not UNSET:
            field_dict["sprint_id"] = sprint_id
        if milestone_id is not UNSET:
            field_dict["milestone_id"] = milestone_id
        if goal_id is not UNSET:
            field_dict["goal_id"] = goal_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.task_update_metadata_type_0_item import TaskUpdateMetadataType0Item  # noqa: PLC0415
        from ..models.task_update_type_data_type_0 import TaskUpdateTypeDataType0  # noqa: PLC0415

        d = dict(src_dict)

        def _parse_project_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        project_id = _parse_project_id(d.pop("project_id", UNSET))

        def _parse_org_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        org_id = _parse_org_id(d.pop("org_id", UNSET))

        def _parse_sub_tasks(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                sub_tasks_type_0 = cast(list[str], data)

                return sub_tasks_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        sub_tasks = _parse_sub_tasks(d.pop("sub_tasks", UNSET))

        def _parse_dependencies(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                dependencies_type_0 = cast(list[str], data)

                return dependencies_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        dependencies = _parse_dependencies(d.pop("dependencies", UNSET))

        def _parse_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        title = _parse_title(d.pop("title", UNSET))

        def _parse_description(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        description = _parse_description(d.pop("description", UNSET))

        def _parse_status(data: object) -> None | TaskStatusEnum | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                status_type_0 = check_task_status_enum(data)

                return status_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | TaskStatusEnum | Unset, data)

        status = _parse_status(d.pop("status", UNSET))

        def _parse_assignee(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        assignee = _parse_assignee(d.pop("assignee", UNSET))

        def _parse_start_date(data: object) -> datetime.date | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                start_date_type_0 = datetime.date.fromisoformat(data)

                return start_date_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.date | None | Unset, data)

        start_date = _parse_start_date(d.pop("start_date", UNSET))

        def _parse_due_date(data: object) -> datetime.date | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                due_date_type_0 = datetime.date.fromisoformat(data)

                return due_date_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.date | None | Unset, data)

        due_date = _parse_due_date(d.pop("due_date", UNSET))

        def _parse_priority(data: object) -> None | PriorityEnum | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                priority_type_0 = check_priority_enum(data)

                return priority_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | PriorityEnum | Unset, data)

        priority = _parse_priority(d.pop("priority", UNSET))

        def _parse_task_type(data: object) -> None | TaskTypeEnum | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                task_type_type_0 = check_task_type_enum(data)

                return task_type_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | TaskTypeEnum | Unset, data)

        task_type = _parse_task_type(d.pop("task_type", UNSET))

        def _parse_tags(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                tags_type_0 = cast(list[str], data)

                return tags_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        tags = _parse_tags(d.pop("tags", UNSET))

        def _parse_type_data(data: object) -> None | TaskUpdateTypeDataType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                type_data_type_0 = TaskUpdateTypeDataType0.from_dict(data)

                return type_data_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | TaskUpdateTypeDataType0 | Unset, data)

        type_data = _parse_type_data(d.pop("type_data", UNSET))

        def _parse_metadata(data: object) -> list[TaskUpdateMetadataType0Item] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                metadata_type_0 = []
                _metadata_type_0 = data
                for metadata_type_0_item_data in _metadata_type_0:
                    metadata_type_0_item = TaskUpdateMetadataType0Item.from_dict(metadata_type_0_item_data)

                    metadata_type_0.append(metadata_type_0_item)

                return metadata_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[TaskUpdateMetadataType0Item] | None | Unset, data)

        metadata = _parse_metadata(d.pop("metadata", UNSET))

        def _parse_created_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        created_by = _parse_created_by(d.pop("created_by", UNSET))

        def _parse_updated_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        updated_by = _parse_updated_by(d.pop("updated_by", UNSET))

        def _parse_is_subtask(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        is_subtask = _parse_is_subtask(d.pop("is_subtask", UNSET))

        def _parse_bug_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        bug_id = _parse_bug_id(d.pop("bug_id", UNSET))

        def _parse_tracker_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        tracker_id = _parse_tracker_id(d.pop("tracker_id", UNSET))

        def _parse_restricted_to(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                restricted_to_type_0 = cast(list[str], data)

                return restricted_to_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        restricted_to = _parse_restricted_to(d.pop("restricted_to", UNSET))

        def _parse_team_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        team_id = _parse_team_id(d.pop("team_id", UNSET))

        def _parse_sprint_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        sprint_id = _parse_sprint_id(d.pop("sprint_id", UNSET))

        def _parse_milestone_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        milestone_id = _parse_milestone_id(d.pop("milestone_id", UNSET))

        def _parse_goal_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        goal_id = _parse_goal_id(d.pop("goal_id", UNSET))

        task_update = cls(
            project_id=project_id,
            org_id=org_id,
            sub_tasks=sub_tasks,
            dependencies=dependencies,
            title=title,
            description=description,
            status=status,
            assignee=assignee,
            start_date=start_date,
            due_date=due_date,
            priority=priority,
            task_type=task_type,
            tags=tags,
            type_data=type_data,
            metadata=metadata,
            created_by=created_by,
            updated_by=updated_by,
            is_subtask=is_subtask,
            bug_id=bug_id,
            tracker_id=tracker_id,
            restricted_to=restricted_to,
            team_id=team_id,
            sprint_id=sprint_id,
            milestone_id=milestone_id,
            goal_id=goal_id,
        )

        task_update.additional_properties = d
        return task_update

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
