# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.webhook_update_status_type_0 import check_webhook_update_status_type_0
from ..models.webhook_update_status_type_0 import WebhookUpdateStatusType0
from ..types import UNSET, Unset
from typing import cast


T = TypeVar("T", bound="WebhookUpdate")


@_attrs_define
class WebhookUpdate:
    """
    Attributes:
        name (None | str | Unset):
        url (None | str | Unset):
        events (list[str] | None | Unset): Dotted event names (`task.updated`) or `<resource>.*` wildcards (`task.*`);
            `GET /v1/webhooks/events` lists the vocabulary. A status change is `task.updated` with `status` in `data.before`
            / `data.after`.
        project_ids (list[str] | None | Unset): Only events of these projects. Omit / null / [] = the whole
            organization, including private projects (a project-restricted webhook never receives unfiled tasks' events).
            Send [] to widen back to the whole organization.
        status (None | Unset | WebhookUpdateStatusType0): Pause / resume. A DISABLED webhook is re-enabled with `active`
            (its failure count resets).
    """

    name: None | str | Unset = UNSET
    url: None | str | Unset = UNSET
    events: list[str] | None | Unset = UNSET
    project_ids: list[str] | None | Unset = UNSET
    status: None | Unset | WebhookUpdateStatusType0 = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        name: None | str | Unset
        if isinstance(self.name, Unset):
            name = UNSET
        else:
            name = self.name

        url: None | str | Unset
        if isinstance(self.url, Unset):
            url = UNSET
        else:
            url = self.url

        events: list[str] | None | Unset
        if isinstance(self.events, Unset):
            events = UNSET
        elif isinstance(self.events, list):
            events = self.events

        else:
            events = self.events

        project_ids: list[str] | None | Unset
        if isinstance(self.project_ids, Unset):
            project_ids = UNSET
        elif isinstance(self.project_ids, list):
            project_ids = self.project_ids

        else:
            project_ids = self.project_ids

        status: None | str | Unset
        if isinstance(self.status, Unset):
            status = UNSET
        elif isinstance(self.status, str):
            status = self.status
        else:
            status = self.status

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if name is not UNSET:
            field_dict["name"] = name
        if url is not UNSET:
            field_dict["url"] = url
        if events is not UNSET:
            field_dict["events"] = events
        if project_ids is not UNSET:
            field_dict["project_ids"] = project_ids
        if status is not UNSET:
            field_dict["status"] = status

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)

        def _parse_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        name = _parse_name(d.pop("name", UNSET))

        def _parse_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        url = _parse_url(d.pop("url", UNSET))

        def _parse_events(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                events_type_0 = cast(list[str], data)

                return events_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        events = _parse_events(d.pop("events", UNSET))

        def _parse_project_ids(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                project_ids_type_0 = cast(list[str], data)

                return project_ids_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        project_ids = _parse_project_ids(d.pop("project_ids", UNSET))

        def _parse_status(data: object) -> None | Unset | WebhookUpdateStatusType0:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                status_type_0 = check_webhook_update_status_type_0(data)

                return status_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | WebhookUpdateStatusType0, data)

        status = _parse_status(d.pop("status", UNSET))

        webhook_update = cls(
            name=name,
            url=url,
            events=events,
            project_ids=project_ids,
            status=status,
        )

        webhook_update.additional_properties = d
        return webhook_update

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
