# GENERATED by scripts/generate.py from spec/openapi.public.json — DO NOT EDIT BY HAND.
# Change the spec snapshot (or the generator) and run `python scripts/generate.py`.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.webhook_out_status import check_webhook_out_status
from ..models.webhook_out_status import WebhookOutStatus
from ..types import UNSET, Unset
from typing import cast
import datetime


T = TypeVar("T", bound="WebhookOut")


@_attrs_define
class WebhookOut:
    """Returned by `webhooks.delete`, `webhooks.read` and `webhooks.update`.

    Example:
        {'api_version': '2026-09-25', 'consecutive_failures': 0, 'created_at': '2026-09-25T12:00:00Z', 'created_by':
            '3f1c2a9e-0b7d-4c1e-9a55-2b8f0d6e4a10', 'events': ['task.*'], 'key_version': 1, 'name': 'Deploy notifier',
            'org_id': 'O0020', 'secret_prefix': 'whsec_Ab3xQ9', 'status': 'active', 'subscription_id': 'WH123456',
            'updated_at': '2026-09-25T12:00:00Z', 'url': 'https://hooks.example.com/tasksmate'}

    Attributes:
        subscription_id (str):
        org_id (str):
        name (str):
        url (str): As registered (an admin's own configuration)
        events (list[str]):
        secret_prefix (str): `whsec_` + 6 characters — the secret itself is never shown again
        status (WebhookOutStatus):
        api_version (str):
        created_by (None | str | Unset):
        project_ids (list[str] | None | Unset):
        key_version (int | Unset):  Default: 1.
        secret_rotated_at (datetime.datetime | None | Unset):
        previous_secret_expires_at (datetime.datetime | None | Unset): Until then deliveries carry a second signature
            (the old secret)
        disabled_reason (None | str | Unset): consecutive_failures · gone (the endpoint answered 410)
        consecutive_failures (int | Unset):  Default: 0.
        last_delivery_at (datetime.datetime | None | Unset):
        last_delivery_status (None | str | Unset):
        last_success_at (datetime.datetime | None | Unset):
        created_at (datetime.datetime | None | Unset):
        updated_at (datetime.datetime | None | Unset):
    """

    subscription_id: str
    org_id: str
    name: str
    url: str
    events: list[str]
    secret_prefix: str
    status: WebhookOutStatus
    api_version: str
    created_by: None | str | Unset = UNSET
    project_ids: list[str] | None | Unset = UNSET
    key_version: int | Unset = 1
    secret_rotated_at: datetime.datetime | None | Unset = UNSET
    previous_secret_expires_at: datetime.datetime | None | Unset = UNSET
    disabled_reason: None | str | Unset = UNSET
    consecutive_failures: int | Unset = 0
    last_delivery_at: datetime.datetime | None | Unset = UNSET
    last_delivery_status: None | str | Unset = UNSET
    last_success_at: datetime.datetime | None | Unset = UNSET
    created_at: datetime.datetime | None | Unset = UNSET
    updated_at: datetime.datetime | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)
    # tasksmate: the response's `ETag` (set by the facade on single reads / writes). Not a property of the resource: it is
    # never serialized by `to_dict` nor read by `from_dict`, and it does not take part in equality.
    etag: str | None = _attrs_field(default=None, init=False, repr=False, eq=False)

    def to_dict(self) -> dict[str, Any]:
        subscription_id = self.subscription_id

        org_id = self.org_id

        name = self.name

        url = self.url

        events = self.events

        secret_prefix = self.secret_prefix

        status: str = self.status

        api_version = self.api_version

        created_by: None | str | Unset
        if isinstance(self.created_by, Unset):
            created_by = UNSET
        else:
            created_by = self.created_by

        project_ids: list[str] | None | Unset
        if isinstance(self.project_ids, Unset):
            project_ids = UNSET
        elif isinstance(self.project_ids, list):
            project_ids = self.project_ids

        else:
            project_ids = self.project_ids

        key_version = self.key_version

        secret_rotated_at: None | str | Unset
        if isinstance(self.secret_rotated_at, Unset):
            secret_rotated_at = UNSET
        elif isinstance(self.secret_rotated_at, datetime.datetime):
            secret_rotated_at = self.secret_rotated_at.isoformat()
        else:
            secret_rotated_at = self.secret_rotated_at

        previous_secret_expires_at: None | str | Unset
        if isinstance(self.previous_secret_expires_at, Unset):
            previous_secret_expires_at = UNSET
        elif isinstance(self.previous_secret_expires_at, datetime.datetime):
            previous_secret_expires_at = self.previous_secret_expires_at.isoformat()
        else:
            previous_secret_expires_at = self.previous_secret_expires_at

        disabled_reason: None | str | Unset
        if isinstance(self.disabled_reason, Unset):
            disabled_reason = UNSET
        else:
            disabled_reason = self.disabled_reason

        consecutive_failures = self.consecutive_failures

        last_delivery_at: None | str | Unset
        if isinstance(self.last_delivery_at, Unset):
            last_delivery_at = UNSET
        elif isinstance(self.last_delivery_at, datetime.datetime):
            last_delivery_at = self.last_delivery_at.isoformat()
        else:
            last_delivery_at = self.last_delivery_at

        last_delivery_status: None | str | Unset
        if isinstance(self.last_delivery_status, Unset):
            last_delivery_status = UNSET
        else:
            last_delivery_status = self.last_delivery_status

        last_success_at: None | str | Unset
        if isinstance(self.last_success_at, Unset):
            last_success_at = UNSET
        elif isinstance(self.last_success_at, datetime.datetime):
            last_success_at = self.last_success_at.isoformat()
        else:
            last_success_at = self.last_success_at

        created_at: None | str | Unset
        if isinstance(self.created_at, Unset):
            created_at = UNSET
        elif isinstance(self.created_at, datetime.datetime):
            created_at = self.created_at.isoformat()
        else:
            created_at = self.created_at

        updated_at: None | str | Unset
        if isinstance(self.updated_at, Unset):
            updated_at = UNSET
        elif isinstance(self.updated_at, datetime.datetime):
            updated_at = self.updated_at.isoformat()
        else:
            updated_at = self.updated_at

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "subscription_id": subscription_id,
                "org_id": org_id,
                "name": name,
                "url": url,
                "events": events,
                "secret_prefix": secret_prefix,
                "status": status,
                "api_version": api_version,
            }
        )
        if created_by is not UNSET:
            field_dict["created_by"] = created_by
        if project_ids is not UNSET:
            field_dict["project_ids"] = project_ids
        if key_version is not UNSET:
            field_dict["key_version"] = key_version
        if secret_rotated_at is not UNSET:
            field_dict["secret_rotated_at"] = secret_rotated_at
        if previous_secret_expires_at is not UNSET:
            field_dict["previous_secret_expires_at"] = previous_secret_expires_at
        if disabled_reason is not UNSET:
            field_dict["disabled_reason"] = disabled_reason
        if consecutive_failures is not UNSET:
            field_dict["consecutive_failures"] = consecutive_failures
        if last_delivery_at is not UNSET:
            field_dict["last_delivery_at"] = last_delivery_at
        if last_delivery_status is not UNSET:
            field_dict["last_delivery_status"] = last_delivery_status
        if last_success_at is not UNSET:
            field_dict["last_success_at"] = last_success_at
        if created_at is not UNSET:
            field_dict["created_at"] = created_at
        if updated_at is not UNSET:
            field_dict["updated_at"] = updated_at

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        subscription_id = d.pop("subscription_id")

        org_id = d.pop("org_id")

        name = d.pop("name")

        url = d.pop("url")

        events = cast(list[str], d.pop("events"))

        secret_prefix = d.pop("secret_prefix")

        status = check_webhook_out_status(d.pop("status"))

        api_version = d.pop("api_version")

        def _parse_created_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        created_by = _parse_created_by(d.pop("created_by", UNSET))

        def _parse_project_ids(data: object) -> list[str] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                project_ids_type_0 = cast(list[str], data)

                return project_ids_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[str] | None | Unset, data)

        project_ids = _parse_project_ids(d.pop("project_ids", UNSET))

        key_version = d.pop("key_version", UNSET)

        def _parse_secret_rotated_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                secret_rotated_at_type_0 = datetime.datetime.fromisoformat(data)

                return secret_rotated_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        secret_rotated_at = _parse_secret_rotated_at(d.pop("secret_rotated_at", UNSET))

        def _parse_previous_secret_expires_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                previous_secret_expires_at_type_0 = datetime.datetime.fromisoformat(data)

                return previous_secret_expires_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        previous_secret_expires_at = _parse_previous_secret_expires_at(d.pop("previous_secret_expires_at", UNSET))

        def _parse_disabled_reason(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        disabled_reason = _parse_disabled_reason(d.pop("disabled_reason", UNSET))

        consecutive_failures = d.pop("consecutive_failures", UNSET)

        def _parse_last_delivery_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                last_delivery_at_type_0 = datetime.datetime.fromisoformat(data)

                return last_delivery_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        last_delivery_at = _parse_last_delivery_at(d.pop("last_delivery_at", UNSET))

        def _parse_last_delivery_status(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        last_delivery_status = _parse_last_delivery_status(d.pop("last_delivery_status", UNSET))

        def _parse_last_success_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                last_success_at_type_0 = datetime.datetime.fromisoformat(data)

                return last_success_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        last_success_at = _parse_last_success_at(d.pop("last_success_at", UNSET))

        def _parse_created_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                created_at_type_0 = datetime.datetime.fromisoformat(data)

                return created_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        created_at = _parse_created_at(d.pop("created_at", UNSET))

        def _parse_updated_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                updated_at_type_0 = datetime.datetime.fromisoformat(data)

                return updated_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        updated_at = _parse_updated_at(d.pop("updated_at", UNSET))

        webhook_out = cls(
            subscription_id=subscription_id,
            org_id=org_id,
            name=name,
            url=url,
            events=events,
            secret_prefix=secret_prefix,
            status=status,
            api_version=api_version,
            created_by=created_by,
            project_ids=project_ids,
            key_version=key_version,
            secret_rotated_at=secret_rotated_at,
            previous_secret_expires_at=previous_secret_expires_at,
            disabled_reason=disabled_reason,
            consecutive_failures=consecutive_failures,
            last_delivery_at=last_delivery_at,
            last_delivery_status=last_delivery_status,
            last_success_at=last_success_at,
            created_at=created_at,
            updated_at=updated_at,
        )

        webhook_out.additional_properties = d
        return webhook_out

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
